// src/routes/guides/+page.svelte
<script lang="ts">
	import { inview } from '$lib/actions/inview';
	import {
		BookSolid,
		StarSolid,
		CheckSolid,
		RocketSolid,
		FireSolid,
		HammerSolid,
		ToolboxSolid,
		ExternalLinkAltSolid,
		GlobeAmericasSolid,
		CompassSolid
	} from 'svelte-awesome-icons';
</script>

<!-- Hero Section -->
<section class="relative overflow-hidden border-b border-primary-main/20">
	<div
		class="absolute inset-0 bg-gradient-to-b from-primary-main/5 via-transparent to-transparent"
	></div>
	<div class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-32">
		<div use:inview class="inview-hidden mx-auto max-w-3xl text-center">
			<div
				class="mb-6 inline-flex items-center gap-2 rounded-full border border-primary-main/30 bg-primary-main/10 px-4 py-1.5 text-sm text-primary-light"
			>
				<BookSolid class="h-4 w-4" />
				<span>Guides & Operations</span>
			</div>
			<h1 class="text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl">
				Guides & <span class="text-primary-main">Operations</span>
			</h1>
			<p class="mt-6 text-lg leading-relaxed text-gray-300">
				Comprehensive guides, active operations, and essential resources to help you navigate the
				galaxy and contribute to IGFV's ongoing missions.
			</p>
		</div>
	</div>
</section>

<!-- Active Operations -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			Active <span class="text-primary-main">Operations</span>
		</h2>
	</div>
	<div class="grid grid-cols-1 gap-6 md:grid-cols-3">
		<div use:inview={{ delay: 100 }} class="inview-hidden group">
			<div
				class="bg-dark/50 flex h-full flex-col rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-3 inline-block self-start rounded-full bg-green-500/10 px-3 py-0.5 text-xs font-medium text-green-400"
				>
					Active
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Deep Space Expedition</h3>
				<div class="mb-3">
					<div class="flex items-center justify-between text-xs text-gray-400">
						<span>Progress</span>
						<span>65%</span>
					</div>
					<div class="mt-1 h-2 w-full overflow-hidden rounded-full bg-dark-slate1">
						<div
							class="h-full w-[65%] rounded-full bg-primary-main transition-all duration-700"
						></div>
					</div>
				</div>
				<div class="flex-1 space-y-1 text-sm text-gray-400">
					<p class="flex items-center gap-2">
						<CheckSolid class="h-3.5 w-3.5 text-green-400" /> Chart course to Colonia
					</p>
					<p class="flex items-center gap-2">
						<CheckSolid class="h-3.5 w-3.5 text-green-400" /> 6/8 waypoints reached
					</p>
					<p class="flex items-center gap-2">
						<span class="inline-block h-3.5 w-3.5 rounded-full border-2 border-gray-500"></span> Final
						approach to Colonia
					</p>
				</div>
				<div class="mt-4 border-t border-primary-main/10 pt-3 text-xs text-gray-500">
					<p>Commander: Don Samen</p>
				</div>
			</div>
		</div>
		<div use:inview={{ delay: 200 }} class="inview-hidden group">
			<div
				class="bg-dark/50 flex h-full flex-col rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-3 inline-block self-start rounded-full bg-blue-500/10 px-3 py-0.5 text-xs font-medium text-blue-400"
				>
					Active
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">BGS Influence Campaign</h3>
				<div class="mb-3">
					<div class="flex items-center justify-between text-xs text-gray-400">
						<span>Progress</span>
						<span>40%</span>
					</div>
					<div class="mt-1 h-2 w-full overflow-hidden rounded-full bg-dark-slate1">
						<div class="h-full w-[40%] rounded-full bg-blue-500 transition-all duration-700"></div>
					</div>
				</div>
				<div class="flex-1 space-y-1 text-sm text-gray-400">
					<p class="flex items-center gap-2">
						<CheckSolid class="h-3.5 w-3.5 text-green-400" /> Initial influence established
					</p>
					<p class="flex items-center gap-2">
						<span class="inline-block h-3.5 w-3.5 rounded-full border-2 border-gray-500"></span> Run trade
						missions
					</p>
					<p class="flex items-center gap-2">
						<span class="inline-block h-3.5 w-3.5 rounded-full border-2 border-gray-500"></span> Complete
						exploration data
					</p>
				</div>
				<div class="mt-4 border-t border-primary-main/10 pt-3 text-xs text-gray-500">
					<p>Commander: Twisted VorteK</p>
				</div>
			</div>
		</div>
		<div use:inview={{ delay: 300 }} class="inview-hidden group">
			<div
				class="bg-dark/50 flex h-full flex-col rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-3 inline-block self-start rounded-full bg-amber-500/10 px-3 py-0.5 text-xs font-medium text-amber-400"
				>
					Planning
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Mining Expedition</h3>
				<div class="mb-3">
					<div class="flex items-center justify-between text-xs text-gray-400">
						<span>Progress</span>
						<span>10%</span>
					</div>
					<div class="mt-1 h-2 w-full overflow-hidden rounded-full bg-dark-slate1">
						<div class="h-full w-[10%] rounded-full bg-amber-500 transition-all duration-700"></div>
					</div>
				</div>
				<div class="flex-1 space-y-1 text-sm text-gray-400">
					<p class="flex items-center gap-2">
						<CheckSolid class="h-3.5 w-3.5 text-green-400" /> Scout potential mining sites
					</p>
					<p class="flex items-center gap-2">
						<span class="inline-block h-3.5 w-3.5 rounded-full border-2 border-gray-500"></span> Organize
						mining wings
					</p>
					<p class="flex items-center gap-2">
						<span class="inline-block h-3.5 w-3.5 rounded-full border-2 border-gray-500"></span> Process
						and sell resources
					</p>
				</div>
				<div class="mt-4 border-t border-primary-main/10 pt-3 text-xs text-gray-500">
					<p>Commander: TBD</p>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Community Guides -->
<section
	class="border-t border-primary-main/20 bg-gradient-to-b from-dark-bg via-primary-main/5 to-dark-bg"
>
	<div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
		<div use:inview class="inview-hidden">
			<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
				Community <span class="text-primary-main">Guides</span>
			</h2>
		</div>
		<div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
			<div use:inview={{ delay: 100 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
					>
						<RocketSolid class="h-5 w-5" />
					</div>
					<h3 class="mb-3 text-lg font-bold text-white">Getting Started with IGFV</h3>
					<ul class="space-y-2 text-sm text-gray-400">
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> How to join the squadron
						</li>
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Setting up Discord and tools
						</li>
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Understanding squadron ranks
						</li>
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Fleet carrier access guide
						</li>
					</ul>
				</div>
			</div>
			<div use:inview={{ delay: 150 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
					>
						<CompassSolid class="h-5 w-5" />
					</div>
					<h3 class="mb-3 text-lg font-bold text-white">Exploration Guide</h3>
					<ul class="space-y-2 text-sm text-gray-400">
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Ship builds for exploration
						</li>
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Using the FSS and DSS
						</li>
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Neutron star boosting
						</li>
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Exploration data selling
						</li>
					</ul>
				</div>
			</div>
			<div use:inview={{ delay: 200 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
					>
						<HammerSolid class="h-5 w-5" />
					</div>
					<h3 class="mb-3 text-lg font-bold text-white">BGS Operations Manual</h3>
					<ul class="space-y-2 text-sm text-gray-400">
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Understanding the BGS
						</li>
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Influence mechanics explained
						</li>
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Conflict zone tactics
						</li>
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Tracking our faction
						</li>
					</ul>
				</div>
			</div>
			<div use:inview={{ delay: 250 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
					>
						<ToolboxSolid class="h-5 w-5" />
					</div>
					<h3 class="mb-3 text-lg font-bold text-white">Engineering & Ship Building</h3>
					<ul class="space-y-2 text-sm text-gray-400">
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Engineer unlock guide
						</li>
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Material farming routes
						</li>
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Ship optimization tips
						</li>
						<li class="flex items-start gap-2">
							<CheckSolid class="mt-0.5 h-3.5 w-3.5 text-primary-main" /> Recommended loadouts
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- External Resources -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			External <span class="text-primary-main">Resources</span>
		</h2>
	</div>
	<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
		<div use:inview={{ delay: 100 }} class="inview-hidden group">
			<a
				href="https://inara.cz"
				target="_blank"
				rel="noopener noreferrer"
				class="bg-dark/50 block h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<GlobeAmericasSolid class="h-5 w-5" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Inara</h3>
				<p class="text-sm text-gray-400">
					Elite Dangerous companion database. Track squadron stats, trade routes, and more.
				</p>
				<div class="mt-4 flex items-center gap-1 text-xs text-primary-light">
					<span>Visit Inara</span>
					<ExternalLinkAltSolid class="h-3 w-3" />
				</div>
			</a>
		</div>
		<div use:inview={{ delay: 150 }} class="inview-hidden group">
			<a
				href="https://eddb.io"
				target="_blank"
				rel="noopener noreferrer"
				class="bg-dark/50 block h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<GlobeAmericasSolid class="h-5 w-5" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">EDDB</h3>
				<p class="text-sm text-gray-400">
					Elite Dangerous Database. Find stations, commodities, and system information.
				</p>
				<div class="mt-4 flex items-center gap-1 text-xs text-primary-light">
					<span>Visit EDDB</span>
					<ExternalLinkAltSolid class="h-3 w-3" />
				</div>
			</a>
		</div>
		<div use:inview={{ delay: 200 }} class="inview-hidden group">
			<a
				href="https://edsy.page"
				target="_blank"
				rel="noopener noreferrer"
				class="bg-dark/50 block h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<FireSolid class="h-5 w-5" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">EDSY</h3>
				<p class="text-sm text-gray-400">Advanced ship outfitting and engineering planner.</p>
				<div class="mt-4 flex items-center gap-1 text-xs text-primary-light">
					<span>Visit EDSY</span>
					<ExternalLinkAltSolid class="h-3 w-3" />
				</div>
			</a>
		</div>
		<div use:inview={{ delay: 250 }} class="inview-hidden group">
			<a
				href="https://canonn.science"
				target="_blank"
				rel="noopener noreferrer"
				class="bg-dark/50 block h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<StarSolid class="h-5 w-5" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Canonn Research</h3>
				<p class="text-sm text-gray-400">
					Research and discovery network for Elite Dangerous mysteries.
				</p>
				<div class="mt-4 flex items-center gap-1 text-xs text-primary-light">
					<span>Visit Canonn</span>
					<ExternalLinkAltSolid class="h-3 w-3" />
				</div>
			</a>
		</div>
	</div>
</section>

<!-- Join Discord CTA -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
	<div use:inview class="inview-hidden">
		<div
			class="to-dark/50 rounded-lg border border-primary-main/30 bg-gradient-to-br from-primary-main/10 p-8 text-center shadow-glow backdrop-blur-sm sm:p-12"
		>
			<h2 class="text-3xl font-bold text-white sm:text-4xl">
				Join Us on <span class="text-primary-main">Discord</span>
			</h2>
			<p class="mx-auto mt-4 max-w-2xl text-gray-300">
				Get access to the latest guides, coordinate with ongoing operations, and connect with fellow
				commanders.
			</p>
			<a
				href="https://discord.gg/igfv"
				target="_blank"
				rel="noopener noreferrer"
				class="mt-6 inline-flex items-center gap-2 rounded-lg bg-primary-main px-8 py-3 font-semibold text-white transition-all duration-300 hover:bg-primary-light hover:shadow-glow-hover"
			>
				<RocketSolid class="h-5 w-5" />
				Join Our Discord
			</a>
		</div>
	</div>
</section>

// src/app/guides/page.tsx
'use client';

import { FaRocket, FaGlobeAmericas, FaCheckCircle, FaClock, FaFire, FaBook, FaToolbox, FaChartLine, FaShoppingCart, FaExternalLinkAlt } from 'react-icons/fa';
import { motion } from 'framer-motion';

export default function GuidesPage() {
  const operations = [
    {
      id: 1,
      title: 'Waungaze BGS Control',
      type: 'BGS',
      status: 'Active',
      progress: 78,
      description: 'Working to increase faction influence in Waungaze system.',
      objectives: [
        'Mission stacking for faction rep',
        'Trade runs between stations',
        'Influence monitoring',
      ],
      commander: 'Skalfinn',
      start: '2025-10-15',
      daysLeft: 12,
    },
    {
      id: 2,
      title: 'Colonia Expedition Prep',
      type: 'Exploration',
      status: 'Planning',
      progress: 35,
      description: 'Preparing fleet for long-range Colonia expedition in December.',
      objectives: [
        'Gather exploration supplies',
        'Plot jump routes',
        'Coordinate team assignments',
        'Test carrier jump mechanics',
      ],
      commander: 'Valhall Command',
      start: '2025-11-01',
      daysLeft: 30,
    },
    {
      id: 3,
      title: 'Mining Operation - LHS 20',
      type: 'Mining',
      status: 'Active',
      progress: 56,
      description: 'Resource gathering mission targeting high-value asteroids.',
      objectives: [
        'Locate pristine metallic rings',
        'Coordinate mining wing',
        'Transport ore to carrier',
        'Process and sell commodities',
      ],
      commander: 'RedMiner',
      start: '2025-10-28',
      daysLeft: 7,
    },
  ];

  const resourceCategories = [
    {
      icon: FaRocket,
      title: 'Ship Builds & Progression',
      description: 'Starter ships to endgame builds',
      items: [
        'Cobra Mk3 → Python → Anaconda progression',
        'Exploration ships: DBX, AspX, Anaconda',
        'Mining setups: Python, Cutter, Type-10',
        'Combat builds: Vulture, Chieftain, Vette',
        'Trading: Python, T9, Cutter',
      ],
    },
    {
      icon: FaToolbox,
      title: 'Engineering & Materials',
      description: 'Maximize your ship performance',
      items: [
        'G5 engineering priorities by role',
        'Material farming locations',
        'Blueprint efficiency guide',
        'Engineer unlock requirements',
        'Experimental effects explained',
      ],
    },
    {
      icon: FaChartLine,
      title: 'Trading & Economy',
      description: 'Profit-making guide',
      items: [
        'High-profit trade routes',
        'Commodity market analysis',
        'Station types and benefits',
        'BGS influence mechanics',
        'Market data resources (EDDB, Inara)',
      ],
    },
    {
      icon: FaShoppingCart,
      title: 'Mining & Resources',
      description: 'Resource gathering strategies',
      items: [
        'Pristine metallic ring locations',
        'Laser vs core mining comparison',
        'Material values and demand',
        'LTD vs platinum profit analysis',
        'Mining hotspot guide',
      ],
    },
  ];

  const externalResources = [
    {
      name: 'EDDB (Elite Dangerous Database)',
      url: 'https://eddb.io',
      description: 'Station data, trade routes, commodities',
    },
    {
      name: 'Inara.Cz',
      url: 'https://inara.cz',
      description: 'Commander profiles, squadron stats, FC registry',
    },
    {
      name: 'EDSM (Elite Dangerous Star Map)',
      url: 'https://edsm.net',
      description: 'Exploration data, system information',
    },
    {
      name: 'Coriolis.io',
      url: 'https://coriolis.io',
      description: 'Ship builder and cost calculator',
    },
  ];

  const statusColor = (status: string) => {
    switch (status) {
      case 'Active':
        return 'bg-green-500/20 text-green-400 border-green-500/40';
      case 'Planning':
        return 'bg-yellow-500/20 text-yellow-400 border-yellow-500/40';
      case 'Ongoing':
        return 'bg-blue-500/20 text-blue-400 border-blue-500/40';
      default:
        return 'bg-gray-500/20 text-gray-400 border-gray-500/40';
    }
  };

  const typeIcon = (type: string) => {
    switch (type) {
      case 'BGS':
        return <FaGlobeAmericas className="text-xl" />;
      case 'Exploration':
        return <FaRocket className="text-xl" />;
      case 'Mining':
        return <FaShoppingCart className="text-xl" />;
      default:
        return <FaFire className="text-xl" />;
    }
  };

  return (
    <div className="min-h-screen py-16 px-4 pt-28">
      <div className="container mx-auto max-w-7xl">
        {/* Hero Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <div className="flex justify-center items-center gap-4 mb-4">
            <FaBook className="text-5xl text-primary-main" />
          </div>
          <h1 className="text-5xl md:text-6xl font-bold text-white mb-4">
            Guides & Operations
          </h1>
          <p className="text-xl text-gray-400 max-w-3xl mx-auto">
            Active operations, community guides, and resources to enhance your Elite Dangerous experience.
          </p>
        </motion.div>

        {/* Active Operations Section */}
        <section className="mb-16">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="mb-8"
          >
            <div className="flex items-center gap-3 mb-4">
              <FaRocket className="text-3xl text-primary-main" />
              <h2 className="text-3xl font-bold text-white">Active Operations</h2>
            </div>
            <p className="text-gray-400 text-lg">
              Current squadron operations and missions. Join us in these coordinated efforts!
            </p>
          </motion.div>

          <div className="grid lg:grid-cols-2 gap-6 mb-12">
            {operations.map((op, index) => (
              <motion.div
                key={op.id}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="bg-dark/50 backdrop-blur-sm border border-primary-main/20 rounded-lg p-6 shadow-glow hover:shadow-glow-hover hover:border-primary-main/60 transition-all group"
              >
                <div className="flex items-start justify-between mb-4">
                  <div className="flex items-center gap-3">
                    <div className="text-primary-main group-hover:text-white transition-colors">{typeIcon(op.type)}</div>
                    <div>
                      <h3 className="text-xl font-bold text-white">{op.title}</h3>
                      <p className="text-sm text-gray-400">Led by {op.commander}</p>
                    </div>
                  </div>
                  <span className={`px-3 py-1 rounded-full text-xs font-semibold border ${statusColor(op.status)}`}>
                    {op.status}
                  </span>
                </div>

                <p className="text-gray-400 mb-4">{op.description}</p>

                <div className="mb-4">
                  <div className="flex justify-between text-sm mb-2">
                    <span className="text-gray-400">Progress</span>
                    <span className="text-primary-light font-semibold">{op.progress}%</span>
                  </div>
                  <div className="w-full bg-dark-slate3 rounded-full h-2">
                    <div
                      className="bg-primary-main h-2 rounded-full transition-all"
                      style={{ width: `${op.progress}%` }}
                    />
                  </div>
                </div>

                <div className="mb-4">
                  <h4 className="text-sm font-semibold text-primary-light mb-2">Objectives:</h4>
                  <ul className="space-y-1">
                    {op.objectives.map((obj, idx) => (
                      <li key={idx} className="text-gray-400 text-sm flex items-start">
                        <FaCheckCircle className="text-primary-main mr-2 mt-1 flex-shrink-0" />
                        {obj}
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="flex items-center gap-2 text-sm text-gray-400">
                  <FaClock />
                  <span>{op.daysLeft === 999 ? 'Ongoing' : `${op.daysLeft} days left`}</span>
                </div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Resource Guides Section */}
        <section className="mb-16">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="mb-8"
          >
            <div className="flex items-center gap-3 mb-4">
              <FaBook className="text-3xl text-primary-main" />
              <h2 className="text-3xl font-bold text-white">Community Guides</h2>
            </div>
            <p className="text-gray-400 text-lg">
              Curated guides and tips to help you succeed in the galaxy.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 gap-6">
            {resourceCategories.map((category, index) => {
              const IconComponent = category.icon;
              return (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: index * 0.1 }}
                  className="bg-dark/50 backdrop-blur-sm border border-primary-main/20 rounded-lg p-6 shadow-glow hover:shadow-glow-hover hover:border-primary-main/60 transition-all group"
                >
                  <div className="flex items-start gap-4 mb-4">
                    <IconComponent className="text-3xl text-primary-main group-hover:text-white flex-shrink-0 transition-colors" />
                    <div>
                      <h3 className="text-xl font-bold text-white mb-1">{category.title}</h3>
                      <p className="text-sm text-gray-400">{category.description}</p>
                    </div>
                  </div>
                  <ul className="space-y-2">
                    {category.items.map((item, idx) => (
                      <li key={idx} className="text-gray-400 text-sm flex items-start">
                        <span className="text-primary-main mr-2">•</span>
                        {item}
                      </li>
                    ))}
                  </ul>
                </motion.div>
              );
            })}
          </div>
        </section>

        {/* External Resources Section */}
        <section>
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="mb-8"
          >
            <div className="flex items-center gap-3 mb-4">
              <FaExternalLinkAlt className="text-3xl text-primary-main" />
              <h2 className="text-3xl font-bold text-white">External Resources</h2>
            </div>
            <p className="text-gray-400 text-lg">
              Essential third-party tools and databases for Elite Dangerous.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 gap-6">
            {externalResources.map((resource, index) => (
              <motion.a
                key={index}
                href={resource.url}
                target="_blank"
                rel="noopener noreferrer"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="bg-dark/50 backdrop-blur-sm border border-primary-main/20 rounded-lg p-6 shadow-glow hover:shadow-glow-hover hover:border-primary-main/60 transition-all group"
              >
                <div className="flex items-start justify-between mb-2">
                  <h3 className="text-lg font-bold text-white group-hover:text-primary-light transition-colors">
                    {resource.name}
                  </h3>
                  <FaExternalLinkAlt className="text-primary-main group-hover:text-white transition-colors" />
                </div>
                <p className="text-gray-400 text-sm">{resource.description}</p>
              </motion.a>
            ))}
          </div>
        </section>

        {/* Join Discord CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="mt-16 text-center bg-dark/50 backdrop-blur-sm border border-primary-main/20 rounded-lg p-8 shadow-glow"
        >
          <h3 className="text-2xl font-bold text-white mb-4">Want to participate?</h3>
          <p className="text-gray-400 mb-6 max-w-2xl mx-auto">
            Join our Discord to get involved in squadron operations and access exclusive guides.
          </p>
          <a
            href="https://discord.gg/invite/Jvrgy6EEQn"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-block px-6 py-3 bg-primary-main hover:bg-primary-darkest text-white rounded-md font-semibold transition-colors"
          >
            Join Discord
          </a>
        </motion.div>
      </div>
    </div>
  );
}
