// src/lib/components/ScrollToTop.svelte
<script lang="ts">
	import { ChevronUpSolid } from 'svelte-awesome-icons';

	let scrollY = $state(0);

	$effect(() => {
		function onScroll() {
			scrollY = window.scrollY;
		}

		window.addEventListener('scroll', onScroll, { passive: true });

		return () => {
			window.removeEventListener('scroll', onScroll);
		};
	});

	let visible = $derived(scrollY > 300);

	function scrollToTop() {
		window.scrollTo({ top: 0, behavior: 'smooth' });
	}
</script>

<button
	class="fixed right-8 bottom-8 z-50 flex h-12 w-12 items-center justify-center rounded-full bg-primary-main text-white shadow-lg transition-all hover:bg-primary-light hover:shadow-glow-hover"
	class:opacity-100={visible}
	class:opacity-0={!visible}
	class:pointer-events-none={!visible}
	onclick={scrollToTop}
	aria-label="Scroll to top"
>
	<ChevronUpSolid class="h-5 w-5" />
</button>

// src/components/ScrollToTop/ScrollToTop.tsx
"use client";

import React, { useEffect, useState } from 'react';
import { FaChevronUp } from 'react-icons/fa';

export default function ScrollToTop() {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const onScroll = () => setVisible(window.scrollY > 300);
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  if (!visible) return null;

  return (
    <button
      aria-label="Scroll to top"
      onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
      className="fixed right-6 bottom-6 z-50 w-12 h-12 rounded-lg bg-primary-main text-white shadow-lg flex items-center justify-center hover:bg-primary-darkest transition-colors"
    >
      <FaChevronUp />
    </button>
  );
}
