// src/app/news/page.tsx
'use client';

import { FaNewspaper, FaFire, FaTrophy, FaRocket, FaClock, FaUser } from 'react-icons/fa';
import { motion } from 'framer-motion';
import Link from 'next/link';

export default function NewsPage() {
  const newsItems = [
    {
      id: 1,
      title: 'Valhall Reaches 100 Members!',
      category: 'Milestone',
      date: '2025-11-02',
      author: 'Skalfinn',
      excerpt: 'Today we celebrate reaching 100 active squadron members! This is a huge achievement for IGFV.',
      content: "We've grown from a small group to a thriving community of 100+ Commanders. Thanks to everyone who joined us on this journey. Our next goal: 150 members by Q1 2026!",
      icon: FaTrophy,
      color: 'border-green-500',
    },
    {
      id: 2,
      title: 'Waungaze BGS Operation Update',
      category: 'Operations',
      date: '2025-10-30',
      author: 'Valhall Command',
      excerpt: "BGS influence now at 78%. We're on track to reach control status within 2 weeks.",
      content: 'Current faction influence is growing steadily. Members have completed 250+ faction missions. At this pace, we should achieve full control by mid-November. Keep up the excellent work!',
      icon: FaRocket,
      color: 'border-blue-500',
    },
    {
      id: 3,
      title: 'Fleet Carrier Services Expanded',
      category: 'Fleet Carrier',
      date: '2025-10-28',
      author: 'Valhall Command',
      excerpt: "We've added new outfitting and repair services to Valhall. Ship customization is now available.",
      content: 'Thanks to upgrades on the Valhall, we can now provide full ship outfitting and advanced repairs. Visit the Fleet Carrier page for service availability and docking procedures.',
      icon: FaFire,
      color: 'border-orange-500',
    },
    {
      id: 4,
      title: 'Mining Operation - LHS 20 Success!',
      category: 'Operations',
      date: '2025-10-25',
      author: 'RedMiner',
      excerpt: 'Mining wing collected 500+ tons of platinum ore. Profits exceeded 150 million credits.',
      content: 'Excellent coordination from the mining wing! We discovered 3 pristine metallic rings and executed flawless extractions. Total profit: 154M credits. Next mining op scheduled for November 15.',
      icon: FaFire,
      color: 'border-yellow-500',
    },
    {
      id: 5,
      title: 'Discord Bot Now Live',
      category: 'Community',
      date: '2025-10-20',
      author: 'TechTeam',
      excerpt: 'New Discord bot with member stats, operation tracking, and event reminders deployed.',
      content: 'The Valhall Bot is now active in our Discord server. Features include: live member counter, operation notifications, event calendar, and member profile lookups. Type /help for commands.',
      icon: FaRocket,
      color: 'border-purple-500',
    },
    {
      id: 6,
      title: 'Colonia Expedition Announced',
      category: 'Expedition',
      date: '2025-10-18',
      author: 'Expedition Command',
      excerpt: 'December 1st: We launch our first squadron-wide expedition to Colonia. Sign-ups open now!',
      content: 'Join 50+ Commanders as we journey 22,000 LY to Colonia. The Valhall will serve as our mobile base. This is a once-in-a-lifetime exploration opportunity. See #expeditions channel to register.',
      icon: FaRocket,
      color: 'border-indigo-500',
    },
  ];

  const getCategoryIcon = (category: string) => {
    switch (category) {
      case 'Milestone':
        return FaTrophy;
      case 'Operations':
        return FaRocket;
      case 'Fleet Carrier':
        return FaFire;
      case 'Community':
        return FaTrophy;
      case 'Expedition':
        return FaRocket;
      default:
        return FaNewspaper;
    }
  };

  const getCategoryColor = (category: string) => {
    switch (category) {
      case 'Milestone':
        return 'bg-green-500/20 text-green-400';
      case 'Operations':
        return 'bg-blue-500/20 text-blue-400';
      case 'Fleet Carrier':
        return 'bg-orange-500/20 text-orange-400';
      case 'Community':
        return 'bg-purple-500/20 text-purple-400';
      case 'Expedition':
        return 'bg-indigo-500/20 text-indigo-400';
      default:
        return 'bg-gray-500/20 text-gray-400';
    }
  };

  return (
    <div className="min-h-screen py-12">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Page Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="mb-12"
        >
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4 flex items-center gap-3">
            <FaNewspaper className="text-norway-red" />
            Squadron News
          </h1>
          <p className="text-gray-300 text-lg">
            Latest updates from Interstellar Goodfellas. Check Discord for real-time announcements.
          </p>
        </motion.div>

        {/* News Feed */}
        <div className="space-y-6">
          {newsItems.map((item, index) => {
            const IconComponent = getCategoryIcon(item.category);
            return (
              <motion.article
                key={item.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.4, delay: 0.05 * index }}
                className="bg-dark/50 backdrop-blur-sm rounded-lg overflow-hidden shadow-glow hover:shadow-glow-hover transition-all border-l-4 border-norway-red"
              >
                <div className="p-6 md:p-8">
                  {/* Header */}
                  <div className="flex items-start justify-between gap-4 mb-4">
                    <div className="flex items-start gap-3 flex-1">
                      <IconComponent className="text-norway-red text-xl flex-shrink-0 mt-1" />
                      <div className="flex-1">
                        <h2 className="text-2xl font-bold text-white mb-2">{item.title}</h2>
                        <div className="flex flex-wrap items-center gap-3 text-sm">
                          <span className={`px-3 py-1 rounded-full font-semibold ${getCategoryColor(item.category)}`}>
                            {item.category}
                          </span>
                          <span className="flex items-center gap-1 text-gray-400">
                            <FaClock className="text-xs" />
                            {new Date(item.date).toLocaleDateString()}
                          </span>
                          <span className="flex items-center gap-1 text-gray-400">
                            <FaUser className="text-xs" />
                            {item.author}
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Excerpt */}
                  <p className="text-gray-300 mb-4">{item.excerpt}</p>

                  {/* Content */}
                  <p className="text-gray-400 text-sm leading-relaxed mb-4">{item.content}</p>

                  {/* Discord Link */}
                  <Link
                    href="https://discord.gg/igfv"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-block px-4 py-2 bg-norway-red/20 text-norway-red hover:bg-norway-red hover:text-white transition-all rounded-lg text-sm font-semibold"
                  >
                    Discuss in Discord →
                  </Link>
                </div>
              </motion.article>
            );
          })}
        </div>

        {/* Info Banner */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.5 }}
          className="mt-12 p-6 bg-norway-blue/10 border border-norway-blue/30 rounded-lg"
        >
          <p className="text-gray-300 text-center">
            📢 For real-time updates and breaking news, join our{' '}
            <Link href="https://discord.gg/igfv" target="_blank" rel="noopener noreferrer" className="text-norway-red hover:underline font-semibold">
              Discord server
            </Link>
            . News is posted daily in #announcements channel.
          </p>
        </motion.div>
      </div>
    </div>
  );
}

// src/routes/news/+page.svelte
<script lang="ts">
	import { inview } from '$lib/actions/inview';
	import {
		NewspaperSolid,
		StarSolid,
		UserSolid,
		CalendarAltSolid,
		DiscordBrands
	} from 'svelte-awesome-icons';

	const news = [
		{
			category: 'Milestone',
			title: 'IGFV Reaches 100 Active Members!',
			date: 'March 12, 3311',
			author: 'Don Samen',
			color: 'text-green-400',
			bg: 'bg-green-500/10',
			border: 'border-green-500/30',
			excerpt:
				'We are proud to announce that IGFV has reached a significant milestone—over 100 active commanders!',
			content:
				"We are proud to announce that IGFV has reached a significant milestone—over 100 active commanders! This achievement reflects the strength of our community and the dedication of every member who has made IGFV their home among the stars. Thank you to everyone who has been part of this journey. Here's to the next 100!"
		},
		{
			category: 'Operations',
			title: 'Colonia Expedition Underway',
			date: 'March 10, 3311',
			author: 'Twisted VorteK',
			color: 'text-blue-400',
			bg: 'bg-blue-500/10',
			border: 'border-blue-500/30',
			excerpt:
				'The ISS Valhall has embarked on a major expedition to Colonia with 8 commanders aboard.',
			content:
				'The ISS Valhall has embarked on a major expedition to Colonia with 8 commanders aboard. The journey will take approximately two weeks with stops at notable waypoints along the way. Participants are enjoying the scenicroute and engaging in deep space exploration activities. Stay tuned for updates from the expedition team.'
		},
		{
			category: 'Fleet Carrier',
			title: 'ISS Valhall Service Update',
			date: 'March 5, 3311',
			author: 'Don Samen',
			color: 'text-orange-400',
			bg: 'bg-orange-500/10',
			border: 'border-orange-500/30',
			excerpt:
				'New services have been added to the ISS Valhall including expanded market options and repair facilities.',
			content:
				'New services have been added to the ISS Valhall including expanded market options and repair facilities. The carrier now offers a wider range of commodities and improved repair capabilities to better serve our commanders. These upgrades will enhance our self-sufficiency during extended expeditions away from the Bubble.'
		},
		{
			category: 'Community',
			title: 'Squadron Movie Night Announced',
			date: 'March 1, 3311',
			author: 'Twisted VorteK',
			color: 'text-purple-400',
			bg: 'bg-purple-500/10',
			border: 'border-purple-500/30',
			excerpt:
				'Join us for our first community movie night on April 15th. Space-themed movies and good company!',
			content:
				'Join us for our first community movie night on April 15th. We will be watching classic space-themed movies together on Discord voice chat. This is a great opportunity to relax, socialize, and enjoy some entertainment with fellow commanders. Details and movie polls will be posted in the #events channel soon.'
		},
		{
			category: 'Expedition',
			title: 'HIP 12345 BGS Campaign Launched',
			date: 'February 28, 3311',
			author: 'Don Samen',
			color: 'text-indigo-400',
			bg: 'bg-indigo-500/10',
			border: 'border-indigo-500/30',
			excerpt:
				'A new BGS influence campaign has begun in the HIP 12345 system. All members are encouraged to participate.',
			content:
				"A new BGS influence campaign has begun in the HIP 12345 system. All members are encouraged to participate in this week-long operation to increase our minor faction's influence. Activities include trade missions, exploration data delivery, and combat support. Check the #operations channel for detailed objectives and coordination."
		},
		{
			category: 'Community',
			title: 'New Commander Orientation Program',
			date: 'February 20, 3311',
			author: 'Twisted VorteK',
			color: 'text-purple-400',
			bg: 'bg-purple-500/10',
			border: 'border-purple-500/30',
			excerpt:
				'Introducing our new orientation program designed to help new members get started in Elite Dangerous.',
			content:
				'Introducing our new orientation program designed to help new members get started in Elite Dangerous. The program includes one-on-one mentorship, guided tutorials on key game mechanics, and scheduled orientation sessions aboard the ISS Valhall. Whether you are a brand new commander or returning after a break, we are here to help you find your way.'
		}
	];
</script>

<!-- Hero Section -->
<section class="relative overflow-hidden border-b border-primary-main/20">
	<div
		class="absolute inset-0 bg-gradient-to-b from-primary-main/5 via-transparent to-transparent"
	></div>
	<div class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-32">
		<div use:inview class="inview-hidden mx-auto max-w-3xl text-center">
			<div
				class="mb-6 inline-flex items-center gap-2 rounded-full border border-primary-main/30 bg-primary-main/10 px-4 py-1.5 text-sm text-primary-light"
			>
				<NewspaperSolid class="h-4 w-4" />
				<span>Squadron News</span>
			</div>
			<h1 class="text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl">
				Squadron <span class="text-primary-main">News</span>
			</h1>
			<p class="mt-6 text-lg leading-relaxed text-gray-300">
				Stay informed with the latest IGFV news, announcements, and updates from across the
				squadron.
			</p>
		</div>
	</div>
</section>

<!-- News Articles -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			Latest <span class="text-primary-main">News</span>
		</h2>
	</div>
	<div class="mx-auto max-w-4xl space-y-8">
		{#each news as article, i (article.title)}
			<article use:inview={{ delay: i * 100 }} class="inview-hidden group">
				<div
					class="bg-dark/50 rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div class="mb-4 flex flex-wrap items-center gap-3">
						<div
							class="inline-block rounded-full {article.bg} px-3 py-0.5 text-xs font-medium {article.color}"
						>
							{article.category}
						</div>
						<span class="flex items-center gap-1 text-xs text-gray-500">
							<CalendarAltSolid class="h-3 w-3" />
							{article.date}
						</span>
						<span class="flex items-center gap-1 text-xs text-gray-500">
							<UserSolid class="h-3 w-3" />
							{article.author}
						</span>
					</div>
					<h3 class="mb-3 text-xl font-bold text-white">{article.title}</h3>
					<p class="text-sm text-gray-400">{article.excerpt}</p>
					<details class="group/details mt-3">
						<summary
							class="flex cursor-pointer list-none items-center gap-2 text-sm font-medium text-primary-light transition-colors hover:text-primary-main"
						>
							<span>Read more</span>
							<svg
								class="h-3.5 w-3.5 transition-transform group-open/details:rotate-180"
								fill="none"
								viewBox="0 0 24 24"
								stroke="currentColor"
								><path
									stroke-linecap="round"
									stroke-linejoin="round"
									stroke-width="2"
									d="M19 9l-7 7-7-7"
								/></svg
							>
						</summary>
						<p
							class="mt-3 border-t border-primary-main/10 pt-3 text-sm leading-relaxed text-gray-400"
						>
							{article.content}
						</p>
					</details>
				</div>
			</article>
		{/each}
	</div>
</section>

<!-- Info Banner -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
	<div use:inview class="inview-hidden">
		<div
			class="rounded-lg border border-blue-500/30 bg-blue-500/5 p-6 text-center backdrop-blur-sm"
		>
			<StarSolid class="mx-auto mb-3 h-8 w-8 text-blue-400" />
			<h3 class="text-xl font-bold text-white">Real-Time Updates on Discord</h3>
			<p class="mt-2 text-sm text-gray-400">
				For the most up-to-date news and announcements, join our Discord server. The <span
					class="font-medium text-blue-400">#announcements</span
				> channel has real-time updates on all squadron activities.
			</p>
			<a
				href="https://discord.gg/igfv"
				target="_blank"
				rel="noopener noreferrer"
				class="mt-4 inline-flex items-center gap-2 rounded-lg bg-primary-main px-6 py-2.5 text-sm font-semibold text-white transition-all duration-300 hover:bg-primary-light hover:shadow-glow-hover"
			>
				<DiscordBrands class="h-4 w-4" />
				Join Our Discord
			</a>
		</div>
	</div>
</section>
