// src/routes/about/+page.svelte
<script lang="ts">
	import { inview } from '$lib/actions/inview';
	import {
		HistorySolid,
		RocketSolid,
		StarSolid,
		UsersSolid,
		GlobeAmericasSolid,
		ClockSolid,
		HandshakeSolid,
		ShieldAltSolid,
		HandsHelpingSolid,
		CheckSolid,
		CompassSolid,
		HammerSolid,
		FireSolid,
		SpaceShuttleSolid
	} from 'svelte-awesome-icons';
</script>

<!-- Hero Section -->
<section class="relative overflow-hidden border-b border-primary-main/20">
	<div
		class="absolute inset-0 bg-gradient-to-b from-primary-main/5 via-transparent to-transparent"
	></div>
	<div class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-32">
		<div use:inview class="inview-hidden mx-auto max-w-3xl text-center">
			<div
				class="mb-6 inline-flex items-center gap-2 rounded-full border border-primary-main/30 bg-primary-main/10 px-4 py-1.5 text-sm text-primary-light"
			>
				<HistorySolid class="h-4 w-4" />
				<span>About IGFV</span>
			</div>
			<h1 class="text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl">
				About <span class="text-primary-main">IGFV</span>
			</h1>
			<p class="mt-6 text-lg leading-relaxed text-gray-300">
				A peaceful squadron dedicated to exploration, community, and camaraderie in Elite Dangerous.
				Founded in 3305 (2019), we've grown from a small group of like-minded commanders into a
				thriving community aboard the Imperial Fleet Carrier ISS Valhall.
			</p>
		</div>
	</div>
</section>

<!-- Squadron Overview -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			Squadron <span class="text-primary-main">Overview</span>
		</h2>
	</div>
	<div class="mx-auto max-w-4xl space-y-6 text-base leading-relaxed text-gray-300">
		<p
			use:inview={{ delay: 100 }}
			class="inview-hidden bg-dark/50 rounded-lg border border-primary-main/20 p-6 shadow-glow backdrop-blur-sm"
		>
			The Imperial Guard Fleet Vanguard (IGFV) is a peaceful player squadron in Elite Dangerous,
			operating primarily in the Core Systems and beyond. Since our founding in 3305 (2019), we have
			focused on building a welcoming community of commanders who share a passion for exploration,
			trade, and the many facets of the galaxy.
		</p>
		<p
			use:inview={{ delay: 200 }}
			class="inview-hidden bg-dark/50 rounded-lg border border-primary-main/20 p-6 shadow-glow backdrop-blur-sm"
		>
			Operating from our fleet carrier, the ISS Valhall (VXX-RHJ), we provide a mobile base of
			operations for our members. Whether you're charting unexplored systems, running trade routes,
			or engineering the perfect ship, IGFV offers a supportive environment where commanders can
			thrive at their own pace.
		</p>
		<p
			use:inview={{ delay: 300 }}
			class="inview-hidden bg-dark/50 rounded-lg border border-primary-main/20 p-6 shadow-glow backdrop-blur-sm"
		>
			We pride ourselves on being an inclusive and diverse community. Our members span multiple time
			zones and playstyles, from casual explorers to dedicated BGS operators. There are no activity
			requirements—we believe that real life comes first, and Elite Dangerous should be a source of
			enjoyment, not obligation.
		</p>
	</div>
</section>

<!-- Founding History -->
<section
	class="border-t border-primary-main/20 bg-gradient-to-b from-dark-bg via-primary-main/5 to-dark-bg"
>
	<div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
		<div use:inview class="inview-hidden">
			<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
				Founding <span class="text-primary-main">History</span>
			</h2>
		</div>
		<div class="grid grid-cols-1 gap-8 md:grid-cols-3">
			<div use:inview={{ delay: 100 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
					>
						<RocketSolid class="h-6 w-6" />
					</div>
					<div
						class="mb-2 inline-block rounded-full bg-primary-main/10 px-3 py-0.5 text-xs font-medium text-primary-light"
					>
						3305
					</div>
					<h3 class="mb-2 text-xl font-bold text-white">2019 — Founded</h3>
					<p class="text-sm text-gray-400">
						IGFV was established by Commander Don Samen with a vision of creating a peaceful,
						community-focused squadron in Elite Dangerous.
					</p>
				</div>
			</div>
			<div use:inview={{ delay: 200 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
					>
						<SpaceShuttleSolid class="h-6 w-6" />
					</div>
					<div
						class="mb-2 inline-block rounded-full bg-primary-main/10 px-3 py-0.5 text-xs font-medium text-primary-light"
					>
						3307
					</div>
					<h3 class="mb-2 text-xl font-bold text-white">2021 — Fleet Carrier</h3>
					<p class="text-sm text-gray-400">
						Acquisition of the ISS Valhall (VXX-RHJ), a majestic Fleet Carrier serving as the
						squadron's mobile headquarters and central hub for all operations.
					</p>
				</div>
			</div>
			<div use:inview={{ delay: 300 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
					>
						<StarSolid class="h-6 w-6" />
					</div>
					<div
						class="mb-2 inline-block rounded-full bg-primary-main/10 px-3 py-0.5 text-xs font-medium text-primary-light"
					>
						3311
					</div>
					<h3 class="mb-2 text-xl font-bold text-white">2025 — Growing Strong</h3>
					<p class="text-sm text-gray-400">
						IGFV continues to expand its ranks, welcoming commanders from all backgrounds and time
						zones, with an ever-growing presence across the galaxy.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Core Values -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			Core <span class="text-primary-main">Values</span>
		</h2>
	</div>
	<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
		<div use:inview={{ delay: 100 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<UsersSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Community First</h3>
				<p class="text-sm text-gray-400">
					We prioritize building a friendly, supportive community where every member feels welcome.
				</p>
			</div>
		</div>
		<div use:inview={{ delay: 200 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<GlobeAmericasSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Peaceful Expansion</h3>
				<p class="text-sm text-gray-400">
					We explore and expand peacefully, focusing on discovery and cooperation rather than
					conflict.
				</p>
			</div>
		</div>
		<div use:inview={{ delay: 300 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<FireSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Diverse Playstyles</h3>
				<p class="text-sm text-gray-400">
					From exploration to trading, mining to BGS—every playstyle is valued and supported.
				</p>
			</div>
		</div>
		<div use:inview={{ delay: 400 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<ClockSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Timezone Coverage</h3>
				<p class="text-sm text-gray-400">
					Active across multiple time zones ensuring there's always someone to fly with.
				</p>
			</div>
		</div>
	</div>
</section>

<!-- Leadership Team -->
<section
	class="border-t border-primary-main/20 bg-gradient-to-b from-dark-bg via-primary-main/5 to-dark-bg"
>
	<div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
		<div use:inview class="inview-hidden">
			<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
				Leadership <span class="text-primary-main">Team</span>
			</h2>
		</div>
		<div class="mx-auto grid max-w-4xl grid-cols-1 gap-8 sm:grid-cols-2">
			<div use:inview={{ delay: 100 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div class="mb-4 flex items-center gap-4">
						<div
							class="flex h-14 w-14 items-center justify-center rounded-full bg-primary-main/20 text-xl font-bold text-primary-light"
						>
							DS
						</div>
						<div>
							<h3 class="text-lg font-bold text-white">Don Samen</h3>
							<p class="text-xs text-gray-400">Founder & Squadron Leader</p>
						</div>
					</div>
					<div
						class="mb-3 inline-block rounded-full border border-yellow-500/30 bg-yellow-500/10 px-3 py-0.5 text-xs font-medium text-yellow-400"
					>
						Founder
					</div>
					<p class="text-sm text-gray-400">
						Founded IGFV in 3305 with a vision of peaceful exploration and community. Leads the
						squadron with dedication and oversees all strategic decisions.
					</p>
				</div>
			</div>
			<div use:inview={{ delay: 200 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div class="mb-4 flex items-center gap-4">
						<div
							class="flex h-14 w-14 items-center justify-center rounded-full bg-primary-main/20 text-xl font-bold text-primary-light"
						>
							TV
						</div>
						<div>
							<h3 class="text-lg font-bold text-white">Twisted VorteK</h3>
							<p class="text-xs text-gray-400">Squadron Manager</p>
						</div>
					</div>
					<div
						class="mb-3 inline-block rounded-full border border-blue-500/30 bg-blue-500/10 px-3 py-0.5 text-xs font-medium text-blue-400"
					>
						Manager
					</div>
					<p class="text-sm text-gray-400">
						Manages day-to-day squadron operations, coordinates activities, and ensures the
						community remains a welcoming place for all commanders.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Primary Activities -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			Primary <span class="text-primary-main">Activities</span>
		</h2>
	</div>
	<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
		<div use:inview={{ delay: 100 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<CompassSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Deep Space Exploration</h3>
				<p class="text-sm text-gray-400">
					Venturing into the black, charting undiscovered systems, and contributing to the
					collective knowledge of the galaxy.
				</p>
			</div>
		</div>
		<div use:inview={{ delay: 200 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<SpaceShuttleSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Trade & Mining</h3>
				<p class="text-sm text-gray-400">
					Operating trade routes and mining operations to build squadron wealth and support fleet
					carrier maintenance.
				</p>
			</div>
		</div>
		<div use:inview={{ delay: 300 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<HammerSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">BGS Operations</h3>
				<p class="text-sm text-gray-400">
					Influencing the Background Simulation to support our minor faction and shape the political
					landscape.
				</p>
			</div>
		</div>
		<div use:inview={{ delay: 400 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<FireSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Engineering & Combat</h3>
				<p class="text-sm text-gray-400">
					Helping members engineer their ships and providing support for combat scenarios when
					needed.
				</p>
			</div>
		</div>
	</div>
</section>

<!-- Playstyle & Culture -->
<section
	class="border-t border-primary-main/20 bg-gradient-to-b from-dark-bg via-primary-main/5 to-dark-bg"
>
	<div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
		<div use:inview class="inview-hidden">
			<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
				Playstyle & <span class="text-primary-main">Culture</span>
			</h2>
		</div>
		<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
			<div use:inview={{ delay: 100 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-green-500/20 text-green-400"
					>
						<ShieldAltSolid class="h-6 w-6" />
					</div>
					<h3 class="mb-2 text-lg font-bold text-white">PvE Focus</h3>
					<p class="text-sm text-gray-400">
						We are a PvE-oriented squadron. While we respect PvPers, our focus is on cooperative
						gameplay and exploration.
					</p>
				</div>
			</div>
			<div use:inview={{ delay: 200 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-blue-500/20 text-blue-400"
					>
						<ClockSolid class="h-6 w-6" />
					</div>
					<h3 class="mb-2 text-lg font-bold text-white">No Activity Requirements</h3>
					<p class="text-sm text-gray-400">
						Real life comes first. There are no mandatory activities or minimum playtime
						requirements.
					</p>
				</div>
			</div>
			<div use:inview={{ delay: 300 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-purple-500/20 text-purple-400"
					>
						<GlobeAmericasSolid class="h-6 w-6" />
					</div>
					<h3 class="mb-2 text-lg font-bold text-white">All Timezones Welcome</h3>
					<p class="text-sm text-gray-400">
						With members spanning the globe, there's almost always someone online to fly with.
					</p>
				</div>
			</div>
			<div use:inview={{ delay: 400 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-amber-500/20 text-amber-400"
					>
						<HandsHelpingSolid class="h-6 w-6" />
					</div>
					<h3 class="mb-2 text-lg font-bold text-white">Mentorship</h3>
					<p class="text-sm text-gray-400">
						New to Elite? Our experienced commanders are always ready to help you find your way.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Mission & Values -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			Mission & <span class="text-primary-main">Values</span>
		</h2>
	</div>
	<div class="mx-auto grid max-w-5xl grid-cols-1 gap-6 md:grid-cols-3">
		<div use:inview={{ delay: 100 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<h3 class="mb-3 text-lg font-bold text-white">Our Mission</h3>
				<p class="text-sm text-gray-400">
					To provide a welcoming home for commanders who value exploration, community, and the
					freedom to play Elite Dangerous their way.
				</p>
			</div>
		</div>
		<div use:inview={{ delay: 200 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<h3 class="mb-3 text-lg font-bold text-white">Our Vision</h3>
				<p class="text-sm text-gray-400">
					A galaxy where commanders from all walks of life can come together, share experiences, and
					create lasting friendships among the stars.
				</p>
			</div>
		</div>
		<div use:inview={{ delay: 300 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<h3 class="mb-3 text-lg font-bold text-white">Our Promise</h3>
				<p class="text-sm text-gray-400">
					No drama, no obligations, no pressure. Just good people exploring the galaxy together.
				</p>
			</div>
		</div>
	</div>
</section>

<!-- Code of Conduct -->
<section
	class="border-t border-primary-main/20 bg-gradient-to-b from-dark-bg via-primary-main/5 to-dark-bg"
>
	<div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
		<div use:inview class="inview-hidden">
			<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
				Code of <span class="text-primary-main">Conduct</span>
			</h2>
		</div>
		<div class="mx-auto max-w-3xl space-y-4">
			<div
				use:inview={{ delay: 100 }}
				class="inview-hidden bg-dark/50 flex items-start gap-3 rounded-lg border border-primary-main/20 p-4 backdrop-blur-sm"
			>
				<CheckSolid class="mt-0.5 h-5 w-5 flex-shrink-0 text-green-400" />
				<div>
					<h4 class="font-medium text-white">Be Respectful</h4>
					<p class="text-sm text-gray-400">
						Treat all members with respect. Harassment, discrimination, and toxic behavior will not
						be tolerated.
					</p>
				</div>
			</div>
			<div
				use:inview={{ delay: 150 }}
				class="inview-hidden bg-dark/50 flex items-start gap-3 rounded-lg border border-primary-main/20 p-4 backdrop-blur-sm"
			>
				<CheckSolid class="mt-0.5 h-5 w-5 flex-shrink-0 text-green-400" />
				<div>
					<h4 class="font-medium text-white">Help Others</h4>
					<p class="text-sm text-gray-400">
						Share your knowledge and experience. We grow stronger when we help each other.
					</p>
				</div>
			</div>
			<div
				use:inview={{ delay: 200 }}
				class="inview-hidden bg-dark/50 flex items-start gap-3 rounded-lg border border-primary-main/20 p-4 backdrop-blur-sm"
			>
				<CheckSolid class="mt-0.5 h-5 w-5 flex-shrink-0 text-green-400" />
				<div>
					<h4 class="font-medium text-white">Stay Active</h4>
					<p class="text-sm text-gray-400">
						While there's no minimum activity requirement, staying engaged with the community helps
						keep IGFV vibrant.
					</p>
				</div>
			</div>
			<div
				use:inview={{ delay: 250 }}
				class="inview-hidden bg-dark/50 flex items-start gap-3 rounded-lg border border-primary-main/20 p-4 backdrop-blur-sm"
			>
				<CheckSolid class="mt-0.5 h-5 w-5 flex-shrink-0 text-green-400" />
				<div>
					<h4 class="font-medium text-white">Represent Well</h4>
					<p class="text-sm text-gray-400">
						When flying under the IGFV tag, you represent the squadron. Act in a way that brings
						honor to our name.
					</p>
				</div>
			</div>
			<div
				use:inview={{ delay: 300 }}
				class="inview-hidden bg-dark/50 flex items-start gap-3 rounded-lg border border-primary-main/20 p-4 backdrop-blur-sm"
			>
				<CheckSolid class="mt-0.5 h-5 w-5 flex-shrink-0 text-green-400" />
				<div>
					<h4 class="font-medium text-white">No Griefing</h4>
					<p class="text-sm text-gray-400">
						We do not engage in or encourage griefing, seal clubbing, or any form of player
						harassment.
					</p>
				</div>
			</div>
			<div
				use:inview={{ delay: 350 }}
				class="inview-hidden bg-dark/50 flex items-start gap-3 rounded-lg border border-primary-main/20 p-4 backdrop-blur-sm"
			>
				<CheckSolid class="mt-0.5 h-5 w-5 flex-shrink-0 text-green-400" />
				<div>
					<h4 class="font-medium text-white">Communicate</h4>
					<p class="text-sm text-gray-400">
						Join us on Discord and stay in touch. Communication is key to a thriving community.
					</p>
				</div>
			</div>
			<div
				use:inview={{ delay: 400 }}
				class="inview-hidden bg-dark/50 flex items-start gap-3 rounded-lg border border-primary-main/20 p-4 backdrop-blur-sm"
			>
				<CheckSolid class="mt-0.5 h-5 w-5 flex-shrink-0 text-green-400" />
				<div>
					<h4 class="font-medium text-white">Have Fun</h4>
					<p class="text-sm text-gray-400">
						Above all, remember that Elite Dangerous is a game. Enjoy the journey and the
						camaraderie.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Join CTA -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<div
			class="to-dark/50 rounded-lg border border-primary-main/30 bg-gradient-to-br from-primary-main/10 p-8 text-center shadow-glow backdrop-blur-sm sm:p-12"
		>
			<h2 class="text-3xl font-bold text-white sm:text-4xl">
				Ready to Join <span class="text-primary-main">IGFV</span>?
			</h2>
			<p class="mx-auto mt-4 max-w-2xl text-gray-300">
				Whether you're a seasoned explorer or a brand new commander, there's a place for you in the
				Imperial Guard Fleet Vanguard. Join us on Discord and become part of our community.
			</p>
			<div class="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row">
				<a
					href="/join"
					class="inline-flex items-center gap-2 rounded-lg bg-primary-main px-8 py-3 font-semibold text-white transition-all duration-300 hover:bg-primary-light hover:shadow-glow-hover"
				>
					<HandshakeSolid class="h-5 w-5" />
					Join IGFV
				</a>
				<a
					href="https://discord.gg/igfv"
					target="_blank"
					rel="noopener noreferrer"
					class="inline-flex items-center gap-2 rounded-lg border border-primary-main/50 px-8 py-3 font-semibold text-primary-light transition-all duration-300 hover:bg-primary-main/10 hover:shadow-glow-hover"
				>
					Join Our Discord
				</a>
			</div>
		</div>
	</div>
</section>

// src/app/about/page.tsx
'use client';

import { 
  FaHistory, 
  FaUsers, 
  FaSpaceShuttle, 
  FaGlobeAmericas, 
  FaRocket, 
  FaClock, 
  FaHandshake,
  FaShieldAlt,
  FaStar,
  FaHandsHelping,
  FaCheck,
  FaChartLine,
  FaCompass,
  FaHammer
} from 'react-icons/fa';
import { motion } from 'framer-motion';

export default function AboutPage() {
  const leadership = [
    { 
      rank: 'Admiral', 
      name: 'Don Samen', 
      role: 'Founder', 
      description: 'Squadron founder and strategic leader',
      image: '🎖️'
    },
    { 
      rank: 'Vice Admiral', 
      name: 'Twisted VorteK', 
      role: 'Manager', 
      description: 'Operations manager and community coordinator',
      image: '⭐'
    },
  ];

  const coreValues = [
    {
      icon: FaUsers,
      title: 'Community First',
      description: 'We prioritize friendly onboarding, mutual support, and creating an inclusive environment where every commander can contribute and grow.',
    },
    {
      icon: FaGlobeAmericas,
      title: 'Peaceful Expansion',
      description: 'Focus on exploration, trade, and peaceful development of new colonial outposts through cooperative BGS efforts.',
    },
    {
      icon: FaSpaceShuttle,
      title: 'Diverse Playstyles',
      description: 'Explorers, traders, miners, combat pilots—all playstyles are welcome, valued, and supported.',
    },
    {
      icon: FaClock,
      title: 'Timezone Coverage',
      description: 'We maintain active operations across multiple timezones globally, ensuring there\'s always someone online to fly with.',
    },
  ];

  const activities = [
    {
      icon: FaCompass,
      title: 'Deep Space Exploration',
      description: 'Charting unknown systems and discovering new frontiers in the galaxy.',
    },
    {
      icon: FaChartLine,
      title: 'Trade & Mining',
      description: 'Profitable trading routes and efficient mining operations to fund squadron activities.',
    },
    {
      icon: FaShieldAlt,
      title: 'BGS Operations',
      description: 'Strategic Background Simulation work to expand our influence peacefully.',
    },
    {
      icon: FaHammer,
      title: 'Engineering & Combat',
      description: 'Ship engineering guidance and cooperative combat training for those who seek it.',
    },
  ];

  return (
    <div className="min-h-screen py-12 pt-28">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Hero Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="mb-16"
        >
          <div className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-8 md:p-12 shadow-glow">
            <div className="flex items-center gap-4 mb-4">
              <FaHistory className="text-4xl md:text-5xl text-primary-main" />
              <h1 className="text-4xl md:text-5xl font-bold text-white">About IGFV</h1>
            </div>
            <p className="text-lg text-gray-400">
              Interstellar Goodfellas - A peaceful squadron dedicated to exploration, colonization, and community since 2019.
            </p>
          </div>
        </motion.div>

        {/* Squadron Overview */}
        <motion.section
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-16"
        >
          <h2 className="text-3xl font-bold text-white mb-6">Squadron Overview</h2>
          <div className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-8 shadow-glow">
            <p className="text-gray-300 text-lg leading-relaxed mb-6">
              Welcome to <span className="text-primary-main font-bold">Interstellar Goodfellas</span>, a peaceful squadron dedicated to exploration and colonization in Elite: Dangerous. 
              Our community is a melting pot of pilots—from bright-eyed newcomers to battle-hardened veterans—united by a passion 
              for discovery, mutual support, and strategic innovation.
            </p>
            <p className="text-gray-300 text-lg leading-relaxed mb-6">
              We operate the fleet carrier <span className="text-primary-main font-bold">Goodfellas Valhall</span> as a mobile hub for exploration, trading, mining, and Background Simulation operations. Our focus is on community building, peaceful expansion, and providing a welcoming environment for commanders of all experience levels.
            </p>
            <p className="text-gray-300 text-lg leading-relaxed">
              What makes IGFV unique is our commitment to building an inclusive haven where every pilot can thrive. Whether you&apos;re charting unexplored 
              systems or returning to the stars after a break, we stand together to advance in a universe defined by endless opportunity and 
              evolving challenges.
            </p>
          </div>
        </motion.section>

        {/* Founding History */}
        <motion.section
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-16"
        >
          <h2 className="text-3xl font-bold text-white mb-6 flex items-center gap-3">
            <FaRocket className="text-primary-main" />
            Founding History
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-6 shadow-glow">
              <div className="text-4xl font-bold text-primary-main mb-4">2019</div>
              <h3 className="text-xl font-bold text-white mb-2">Squadron Founded</h3>
              <p className="text-gray-400">
                CMDR Don Samen established Interstellar Goodfellas with a vision of peaceful expansion and community-first gameplay.
              </p>
            </div>
            <div className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-6 shadow-glow">
              <div className="text-4xl font-bold text-primary-main mb-4">2021</div>
              <h3 className="text-xl font-bold text-white mb-2">Fleet Carrier Acquired</h3>
              <p className="text-gray-400">
                Goodfellas Valhall joins the fleet, becoming our mobile operations center and home base for deep space missions.
              </p>
            </div>
            <div className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-6 shadow-glow">
              <div className="text-4xl font-bold text-primary-main mb-4">2025</div>
              <h3 className="text-xl font-bold text-white mb-2">Growing Strong</h3>
              <p className="text-gray-400">
                Active community of 100+ members, with ongoing BGS operations and regular exploration expeditions across the galaxy.
              </p>
            </div>
          </div>
        </motion.section>

        {/* Core Values */}
        <motion.section
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-16"
        >
          <h2 className="text-3xl font-bold text-white mb-6">Core Values</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {coreValues.map((value, idx) => {
              const Icon = value.icon;
              return (
                <motion.div
                  key={idx}
                  initial={{ opacity: 0, y: 10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.4, delay: 0.1 * idx }}
                  className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-6 shadow-glow hover:shadow-glow-hover hover:border-primary-main/60 transition-all group"
                >
                  <div className="flex items-start gap-4">
                    <Icon className="text-primary-main group-hover:text-white text-3xl flex-shrink-0 mt-1 transition-colors" />
                    <div>
                      <h3 className="text-xl font-bold text-white mb-2">{value.title}</h3>
                      <p className="text-gray-400">{value.description}</p>
                    </div>
                  </div>
                </motion.div>
              );
            })}
          </div>
        </motion.section>

        {/* Leadership Team */}
        <motion.section
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-16"
        >
          <h2 className="text-3xl font-bold text-white mb-6 flex items-center gap-3">
            <FaUsers className="text-primary-main" />
            Leadership Team
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {leadership.map((leader, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, scale: 0.95 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: 0.1 * idx }}
                className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-8 shadow-glow hover:shadow-glow-hover hover:border-primary-main/60 transition-all group"
              >
                <div className="flex items-start gap-6">
                  <div className="text-6xl">{leader.image}</div>
                  <div className="flex-1">
                    <span className="inline-block px-3 py-1 bg-primary-main/20 border border-primary-main/40 text-primary-light text-sm font-semibold rounded-full mb-3">
                      {leader.rank}
                    </span>
                    <h3 className="text-2xl font-bold text-white mb-1">CMDR {leader.name}</h3>
                    <p className="text-primary-light font-semibold mb-2">{leader.role}</p>
                    <p className="text-gray-400 text-sm">{leader.description}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* Primary Activities */}
        <motion.section
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-16"
        >
          <h2 className="text-3xl font-bold text-white mb-6">Primary Activities</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {activities.map((activity, idx) => {
              const Icon = activity.icon;
              return (
                <motion.div
                  key={idx}
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.4, delay: 0.1 * idx }}
                  className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-6 shadow-glow hover:shadow-glow-hover hover:border-primary-main/60 transition-all group"
                >
                  <div className="flex items-start gap-4">
                    <Icon className="text-primary-main group-hover:text-white text-2xl flex-shrink-0 mt-1 transition-colors" />
                    <div>
                      <h3 className="text-xl font-bold text-white mb-2">{activity.title}</h3>
                      <p className="text-gray-400">{activity.description}</p>
                    </div>
                  </div>
                </motion.div>
              );
            })}
          </div>
        </motion.section>

        {/* Playstyle & Culture */}
        <motion.section
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-16"
        >
          <h2 className="text-3xl font-bold text-white mb-6">Playstyle & Culture</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-6 shadow-glow">
              <FaHandshake className="text-primary-main text-3xl mb-4" />
              <h3 className="text-xl font-bold text-white mb-3">PvE Focus</h3>
              <p className="text-gray-400">
                We specialize in PvE content with a peaceful approach to gameplay. While we respect all playstyles, our operations focus on cooperative activities and exploration.
              </p>
            </div>
            <div className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-6 shadow-glow">
              <FaClock className="text-primary-main text-3xl mb-4" />
              <h3 className="text-xl font-bold text-white mb-3">No Activity Requirements</h3>
              <p className="text-gray-400">
                Real life comes first. We understand that everyone has different schedules and commitments. Participate as much or as little as you like—there&apos;s no pressure.
              </p>
            </div>
            <div className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-6 shadow-glow">
              <FaGlobeAmericas className="text-primary-main text-3xl mb-4" />
              <h3 className="text-xl font-bold text-white mb-3">All Timezones Welcome</h3>
              <p className="text-gray-400">
                With members spanning multiple continents, you&apos;ll always find fellow commanders online regardless of your timezone.
              </p>
            </div>
            <div className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-6 shadow-glow">
              <FaHandsHelping className="text-primary-main text-3xl mb-4" />
              <h3 className="text-xl font-bold text-white mb-3">Mentorship for New Players</h3>
              <p className="text-gray-400">
                New to Elite Dangerous? Our experienced commanders offer personalized guidance to help you master the game and find your path in the galaxy.
              </p>
            </div>
          </div>
        </motion.section>

        {/* Mission & Values (from homepage) */}
        <motion.section
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-16"
        >
          <h2 className="text-3xl font-bold text-white mb-6">Mission & Values</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[
              {
                title: "Supporting New Pilots",
                description: "Dedicated mentorship program and resources to help new commanders find their path in the galaxy",
                icon: <FaHandsHelping className="w-8 h-8" />
              },
              {
                title: "Peaceful Expansion",
                description: "Focus on exploration, trade, and peaceful development of new colonial outposts",
                icon: <FaStar className="w-8 h-8" />
              },
              {
                title: "Community First",
                description: "Creating an inclusive environment where every commander can contribute and grow",
                icon: <FaUsers className="w-8 h-8" />
              }
            ].map((value, index) => (
              <motion.div
                key={value.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-6 shadow-glow hover:shadow-glow-hover hover:border-primary-main/60 transition-all"
              >
                <div className="text-primary-light mb-4">{value.icon}</div>
                <h3 className="text-xl font-bold text-white mb-2">{value.title}</h3>
                <p className="text-gray-400">{value.description}</p>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* Code of Conduct / Community Guidelines */}
        <motion.section
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-16"
        >
          <h2 className="text-3xl font-bold text-white mb-6 flex items-center gap-3">
            <FaShieldAlt className="text-primary-main" />
            Code of Conduct & Community Guidelines
          </h2>
          <div className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-8 shadow-glow">
            <p className="text-gray-300 mb-6">
              Our community thrives on mutual respect and cooperation. All members are expected to follow these guidelines:
            </p>
            <ul className="space-y-4">
              <li className="flex items-start gap-3">
                <FaCheck className="text-primary-main mt-1 flex-shrink-0" />
                <span className="text-gray-300">Keep your Inara profile updated to help plan future routes and events.</span>
              </li>
              <li className="flex items-start gap-3">
                <FaCheck className="text-primary-main mt-1 flex-shrink-0" />
                <span className="text-gray-300">Follow the accepted PvP code (refer to galaxy-intel for details); when engaging in BGS activities, switch to the open channel.</span>
              </li>
              <li className="flex items-start gap-3">
                <FaCheck className="text-primary-main mt-1 flex-shrink-0" />
                <span className="text-gray-300">New pilots should secure the recommended ships in order: Cobra Mk3, Python, then Anaconda—refer to ship-builds for more information.</span>
              </li>
              <li className="flex items-start gap-3">
                <FaCheck className="text-primary-main mt-1 flex-shrink-0" />
                <span className="text-gray-300">Do not share the server invite without permission from Rear Admirals, Vice Admirals, or the Admiral to maintain our community&apos;s integrity.</span>
              </li>
              <li className="flex items-start gap-3">
                <FaCheck className="text-primary-main mt-1 flex-shrink-0" />
                <span className="text-gray-300">Ensure your Discord name reflects your in-game identity for consistency.</span>
              </li>
              <li className="flex items-start gap-3">
                <FaCheck className="text-primary-main mt-1 flex-shrink-0" />
                <span className="text-gray-300">Treat all members with respect regardless of experience level, timezone, or playstyle preferences.</span>
              </li>
              <li className="flex items-start gap-3">
                <FaCheck className="text-primary-main mt-1 flex-shrink-0" />
                <span className="text-gray-300">Anti-griefing policy: We do not engage in or tolerate griefing behavior. Focus on cooperative gameplay and community building.</span>
              </li>
            </ul>
          </div>
        </motion.section>

        {/* Join CTA */}
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center"
        >
          <div className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-8 md:p-12 shadow-glow">
            <h3 className="text-3xl font-bold text-white mb-4">Ready to Join Us?</h3>
            <p className="text-gray-400 mb-6 max-w-2xl mx-auto text-lg">
              Whether you&apos;re a seasoned commander or just starting your journey, there&apos;s a place for you among the Goodfellas.
            </p>
            <a
              href="https://discord.gg/invite/Jvrgy6EEQn"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-block px-8 py-4 bg-primary-main hover:bg-primary-darkest text-white rounded-md font-semibold transition-colors shadow-glow hover:shadow-glow-hover text-lg"
            >
              Join Our Discord
            </a>
          </div>
        </motion.section>
      </div>
    </div>
  );
}
