// src/app/gallery/page.tsx
'use client';

import { FaImages, FaUser, FaCalendarAlt, FaExternalLinkAlt } from 'react-icons/fa';
import { motion } from 'framer-motion';

export default function GalleryPage() {
  const galleries = [
    {
      title: 'Fleet Carrier Valhall',
      description: 'Exterior and interior shots of our flagship carrier.',
      images: 6,
      color: 'from-norway-red/20',
    },
    {
      title: 'Exploration Highlights',
      description: 'Breathtaking discoveries and deep space views.',
      images: 8,
      color: 'from-norway-blue/20',
    },
    {
      title: 'Mining Operations',
      description: 'Wing mining activities and impressive asteroid finds.',
      images: 5,
      color: 'from-yellow-500/20',
    },
    {
      title: 'Community Events',
      description: 'Squadron members participating in operations.',
      images: 12,
      color: 'from-green-500/20',
    },
    {
      title: 'Ship Collections',
      description: 'Showcase of member ships and configurations.',
      images: 7,
      color: 'from-purple-500/20',
    },
    {
      title: 'BGS Operations',
      description: 'Control stations and faction warfare moments.',
      images: 4,
      color: 'from-orange-500/20',
    },
  ];

  const recentUploads = [
    {
      title: 'Valhall at Waungaze Station',
      author: 'CMDR Skalfinn',
      date: '2025-11-02',
      category: 'Fleet Carrier',
    },
    {
      title: 'Mining Wing in Pristine Ring',
      author: 'CMDR RedMiner',
      date: '2025-10-31',
      category: 'Mining',
    },
    {
      title: 'Distant Star System Discovery',
      author: 'CMDR Explorer42',
      date: '2025-10-29',
      category: 'Exploration',
    },
    {
      title: 'Squadron Formation Flyby',
      author: 'CMDR FleetLeader',
      date: '2025-10-27',
      category: 'Community',
    },
  ];

  return (
    <div className="min-h-screen py-12 pt-28">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Page Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="mb-12"
        >
          <div className="bg-gradient-to-r from-primary-main/20 to-primary-main/5 border border-primary-main/30 rounded-lg p-8 md:p-12 shadow-glow">
            <div className="flex items-center gap-4 mb-4">
              <FaImages className="text-4xl md:text-5xl text-primary-main" />
              <h1 className="text-4xl md:text-5xl font-bold text-white">Gallery</h1>
            </div>
            <p className="text-lg text-gray-400">Screenshots and photos from squadron operations, exploration, and community events.</p>
          </div>
        </motion.div>

        {/* Gallery Categories */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="mb-16"
        >
          <h2 className="text-3xl font-bold text-white mb-8">Image Collections</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {galleries.map((gallery, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.4, delay: 0.05 * idx }}
                className="group cursor-pointer"
              >
                <div className={`bg-gradient-to-br ${gallery.color} to-dark/50 border border-primary-main/20 rounded-lg p-6 h-full shadow-glow hover:shadow-glow-hover hover:border-primary-main/60 transition-all`}>
                  <div className="flex items-start justify-between mb-4">
                    <h3 className="text-xl font-bold text-white flex-1">{gallery.title}</h3>
                    <span className="ml-2 px-3 py-1 bg-primary-main/20 text-primary-light text-sm font-bold rounded-lg whitespace-nowrap">
                      {gallery.images} photos
                    </span>
                  </div>
                  <p className="text-gray-400 mb-4 text-sm">{gallery.description}</p>
                  <div className="flex items-center gap-2 text-primary-main group-hover:text-white text-sm font-semibold group-hover:gap-3 transition-all">
                    <span>View Collection</span>
                    <FaExternalLinkAlt className="text-xs opacity-0 group-hover:opacity-100 transition-opacity" />
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Recent Uploads */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mb-12"
        >
          <h2 className="text-3xl font-bold text-white mb-8">Recent Uploads</h2>
          <div className="space-y-4">
            {recentUploads.map((upload, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.4, delay: 0.05 * idx }}
                className="bg-dark/50 backdrop-blur-sm rounded-lg p-6 shadow-glow border border-primary-main/20 hover:border-primary-main/60 transition-all hover:bg-dark/60 group"
              >
                <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                  <div className="flex-1">
                    <h3 className="text-lg font-bold text-white mb-2">{upload.title}</h3>
                    <div className="flex flex-wrap items-center gap-3 text-sm text-gray-400">
                      <span className="flex items-center gap-1">
                        <FaUser className="text-primary-main group-hover:text-white transition-colors" />
                        CMDR {upload.author}
                      </span>
                      <span className="flex items-center gap-1">
                        <FaCalendarAlt className="text-primary-main group-hover:text-white transition-colors" />
                        {new Date(upload.date).toLocaleDateString()}
                      </span>
                    </div>
                  </div>
                  <span className="px-3 py-1 bg-primary-main/20 text-primary-light text-xs font-semibold rounded-lg whitespace-nowrap">
                    {upload.category}
                  </span>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Upload Info */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="bg-dark/50 backdrop-blur-sm rounded-lg p-8 shadow-glow border border-primary-main/20"
        >
          <h2 className="text-2xl font-bold text-white mb-6">Submit Your Screenshots</h2>
          <p className="text-gray-400 mb-6">
            Have amazing screenshots from your Elite Dangerous adventures? Share them with the community!
          </p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
            <div>
              <h3 className="text-white font-bold mb-2">1. Screenshot</h3>
              <p className="text-gray-400 text-sm">Take a screenshot in-game or import existing images.</p>
            </div>
            <div>
              <h3 className="text-white font-bold mb-2">2. Upload</h3>
              <p className="text-gray-400 text-sm">Join Discord and visit #gallery channel to upload.</p>
            </div>
            <div>
              <h3 className="text-white font-bold mb-2">3. Share</h3>
              <p className="text-gray-400 text-sm">Your submission appears in community gallery instantly!</p>
            </div>
          </div>
          <div className="p-4 bg-primary-main/10 rounded-lg border border-primary-main/30">
            <p className="text-gray-400 text-sm">
              📸 <strong>Guidelines:</strong> High-res screenshots (1080p+), no real-world content, credit original photographers.
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}

// src/routes/gallery/+page.svelte
<script lang="ts">
	import { inview } from '$lib/actions/inview';
	import {
		ImagesSolid,
		ImageSolid,
		StarSolid,
		CalendarAltSolid,
		UserSolid,
		CheckSolid,
		SpaceShuttleSolid,
		CompassSolid,
		FireSolid,
		HammerSolid,
		DiscordBrands
	} from 'svelte-awesome-icons';
</script>

<!-- Hero Section -->
<section class="relative overflow-hidden border-b border-primary-main/20">
	<div
		class="absolute inset-0 bg-gradient-to-b from-primary-main/5 via-transparent to-transparent"
	></div>
	<div class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-32">
		<div use:inview class="inview-hidden mx-auto max-w-3xl text-center">
			<div
				class="mb-6 inline-flex items-center gap-2 rounded-full border border-primary-main/30 bg-primary-main/10 px-4 py-1.5 text-sm text-primary-light"
			>
				<ImagesSolid class="h-4 w-4" />
				<span>Gallery</span>
			</div>
			<h1 class="text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl">
				IGFV <span class="text-primary-main">Gallery</span>
			</h1>
			<p class="mt-6 text-lg leading-relaxed text-gray-300">
				Capturing the beauty of the galaxy through the eyes of our commanders. Browse screenshots
				from our expeditions, operations, and everyday adventures.
			</p>
		</div>
	</div>
</section>

<!-- Gallery Categories -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			Gallery <span class="text-primary-main">Categories</span>
		</h2>
	</div>
	<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
		<div use:inview={{ delay: 100 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<SpaceShuttleSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Fleet Carrier</h3>
				<p class="text-sm text-gray-400">Images of the ISS Valhall and fleet carrier operations.</p>
				<div
					class="mt-4 inline-block rounded-full bg-primary-main/10 px-3 py-0.5 text-xs font-medium text-primary-light"
				>
					24 photos
				</div>
			</div>
		</div>
		<div use:inview={{ delay: 150 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<CompassSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Exploration</h3>
				<p class="text-sm text-gray-400">Breathtaking views from deep space expeditions.</p>
				<div
					class="mt-4 inline-block rounded-full bg-primary-main/10 px-3 py-0.5 text-xs font-medium text-primary-light"
				>
					36 photos
				</div>
			</div>
		</div>
		<div use:inview={{ delay: 200 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<FireSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Mining</h3>
				<p class="text-sm text-gray-400">Asteroid mining operations and resource extraction.</p>
				<div
					class="mt-4 inline-block rounded-full bg-primary-main/10 px-3 py-0.5 text-xs font-medium text-primary-light"
				>
					18 photos
				</div>
			</div>
		</div>
		<div use:inview={{ delay: 250 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<StarSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Events</h3>
				<p class="text-sm text-gray-400">
					Squadron gatherings, expeditions, and community moments.
				</p>
				<div
					class="mt-4 inline-block rounded-full bg-primary-main/10 px-3 py-0.5 text-xs font-medium text-primary-light"
				>
					30 photos
				</div>
			</div>
		</div>
		<div use:inview={{ delay: 300 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<ImageSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Ship Collections</h3>
				<p class="text-sm text-gray-400">Showcasing our commanders' ships and loadouts.</p>
				<div
					class="mt-4 inline-block rounded-full bg-primary-main/10 px-3 py-0.5 text-xs font-medium text-primary-light"
				>
					42 photos
				</div>
			</div>
		</div>
		<div use:inview={{ delay: 350 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<HammerSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">BGS</h3>
				<p class="text-sm text-gray-400">Background Simulation campaign snapshots.</p>
				<div
					class="mt-4 inline-block rounded-full bg-primary-main/10 px-3 py-0.5 text-xs font-medium text-primary-light"
				>
					12 photos
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Recent Uploads -->
<section
	class="border-t border-primary-main/20 bg-gradient-to-b from-dark-bg via-primary-main/5 to-dark-bg"
>
	<div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
		<div use:inview class="inview-hidden">
			<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
				Recent <span class="text-primary-main">Uploads</span>
			</h2>
		</div>
		<div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
			<div use:inview={{ delay: 100 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-3 flex aspect-video items-center justify-center rounded-lg bg-primary-main/10"
					>
						<ImageSolid class="h-10 w-10 text-primary-main/30" />
					</div>
					<div
						class="mb-2 inline-block rounded-full bg-green-500/10 px-2.5 py-0.5 text-xs font-medium text-green-400"
					>
						Exploration
					</div>
					<h3 class="text-lg font-bold text-white">Nebula Sunrise</h3>
					<div class="mt-2 flex items-center gap-4 text-xs text-gray-500">
						<span class="flex items-center gap-1"><UserSolid class="h-3 w-3" /> CMDR Don Samen</span
						>
						<span class="flex items-center gap-1"
							><CalendarAltSolid class="h-3 w-3" /> Mar 10, 3311</span
						>
					</div>
				</div>
			</div>
			<div use:inview={{ delay: 150 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-3 flex aspect-video items-center justify-center rounded-lg bg-primary-main/10"
					>
						<ImageSolid class="h-10 w-10 text-primary-main/30" />
					</div>
					<div
						class="mb-2 inline-block rounded-full bg-blue-500/10 px-2.5 py-0.5 text-xs font-medium text-blue-400"
					>
						Fleet Carrier
					</div>
					<h3 class="text-lg font-bold text-white">Valhall Docking Bay</h3>
					<div class="mt-2 flex items-center gap-4 text-xs text-gray-500">
						<span class="flex items-center gap-1"
							><UserSolid class="h-3 w-3" /> CMDR Twisted VorteK</span
						>
						<span class="flex items-center gap-1"
							><CalendarAltSolid class="h-3 w-3" /> Mar 8, 3311</span
						>
					</div>
				</div>
			</div>
			<div use:inview={{ delay: 200 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-3 flex aspect-video items-center justify-center rounded-lg bg-primary-main/10"
					>
						<ImageSolid class="h-10 w-10 text-primary-main/30" />
					</div>
					<div
						class="mb-2 inline-block rounded-full bg-amber-500/10 px-2.5 py-0.5 text-xs font-medium text-amber-400"
					>
						Mining
					</div>
					<h3 class="text-lg font-bold text-white">Void Opal Score</h3>
					<div class="mt-2 flex items-center gap-4 text-xs text-gray-500">
						<span class="flex items-center gap-1"><UserSolid class="h-3 w-3" /> CMDR StarMiner</span
						>
						<span class="flex items-center gap-1"
							><CalendarAltSolid class="h-3 w-3" /> Mar 5, 3311</span
						>
					</div>
				</div>
			</div>
			<div use:inview={{ delay: 250 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-3 flex aspect-video items-center justify-center rounded-lg bg-primary-main/10"
					>
						<ImageSolid class="h-10 w-10 text-primary-main/30" />
					</div>
					<div
						class="mb-2 inline-block rounded-full bg-purple-500/10 px-2.5 py-0.5 text-xs font-medium text-purple-400"
					>
						Events
					</div>
					<h3 class="text-lg font-bold text-white">Squadron Group Photo</h3>
					<div class="mt-2 flex items-center gap-4 text-xs text-gray-500">
						<span class="flex items-center gap-1"><UserSolid class="h-3 w-3" /> CMDR Don Samen</span
						>
						<span class="flex items-center gap-1"
							><CalendarAltSolid class="h-3 w-3" /> Feb 28, 3311</span
						>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Submit Your Screenshots -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-6 text-center text-3xl font-bold text-white sm:text-4xl">
			Submit Your <span class="text-primary-main">Screenshots</span>
		</h2>
		<p class="mx-auto mb-12 max-w-2xl text-center text-gray-400">
			Want to share your best screenshots with the squadron? Here's how:
		</p>
	</div>
	<div class="grid grid-cols-1 gap-6 sm:grid-cols-3">
		<div use:inview={{ delay: 100 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-primary-main/20 text-xl font-bold text-primary-light"
				>
					1
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Capture</h3>
				<p class="text-sm text-gray-400">
					Take your screenshot using the in-game camera suite or your preferred capture tool.
				</p>
			</div>
		</div>
		<div use:inview={{ delay: 200 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-primary-main/20 text-xl font-bold text-primary-light"
				>
					2
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Upload</h3>
				<p class="text-sm text-gray-400">
					Share your image in the Discord <span class="font-medium text-primary-light"
						>#screenshots</span
					> channel.
				</p>
			</div>
		</div>
		<div use:inview={{ delay: 300 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-primary-main/20 text-xl font-bold text-primary-light"
				>
					3
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Get Featured</h3>
				<p class="text-sm text-gray-400">
					The best screenshots are featured on this page and our social media channels.
				</p>
			</div>
		</div>
	</div>
	<div use:inview={{ delay: 250 }} class="inview-hidden mt-8">
		<div class="bg-dark/50 rounded-lg border border-primary-main/20 p-6 backdrop-blur-sm">
			<h4 class="mb-3 font-semibold text-white">Submission Guidelines</h4>
			<ul class="space-y-2 text-sm text-gray-400">
				<li class="flex items-start gap-2">
					<CheckSolid class="mt-0.5 h-4 w-4 flex-shrink-0 text-green-400" /> High-resolution images recommended
					(1920x1080 or higher)
				</li>
				<li class="flex items-start gap-2">
					<CheckSolid class="mt-0.5 h-4 w-4 flex-shrink-0 text-green-400" /> No offensive or inappropriate
					content
				</li>
				<li class="flex items-start gap-2">
					<CheckSolid class="mt-0.5 h-4 w-4 flex-shrink-0 text-green-400" /> Include a short description
					and your CMDR name
				</li>
				<li class="flex items-start gap-2">
					<CheckSolid class="mt-0.5 h-4 w-4 flex-shrink-0 text-green-400" /> By submitting, you grant
					IGFV permission to share your screenshots
				</li>
			</ul>
		</div>
	</div>
	<div use:inview={{ delay: 300 }} class="inview-hidden mt-6 text-center">
		<a
			href="https://discord.gg/igfv"
			target="_blank"
			rel="noopener noreferrer"
			class="inline-flex items-center gap-2 rounded-lg bg-primary-main px-8 py-3 font-semibold text-white transition-all duration-300 hover:bg-primary-light hover:shadow-glow-hover"
		>
			<DiscordBrands class="h-5 w-5" />
			Share on Discord
		</a>
	</div>
</section>
