// src/routes/resources/+page.svelte
<script lang="ts">
	import { inview } from '$lib/actions/inview';
	import {
		BookSolid,
		CheckSolid,
		StarSolid,
		RocketSolid,
		ExternalLinkAltSolid,
		CompassSolid,
		HammerSolid,
		FireSolid,
		GlobeAmericasSolid,
		ToolboxSolid,
		QuestionCircleSolid
	} from 'svelte-awesome-icons';
</script>

<!-- Hero Section -->
<section class="relative overflow-hidden border-b border-primary-main/20">
	<div
		class="absolute inset-0 bg-gradient-to-b from-primary-main/5 via-transparent to-transparent"
	></div>
	<div class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-32">
		<div use:inview class="inview-hidden mx-auto max-w-3xl text-center">
			<div
				class="mb-6 inline-flex items-center gap-2 rounded-full border border-primary-main/30 bg-primary-main/10 px-4 py-1.5 text-sm text-primary-light"
			>
				<BookSolid class="h-4 w-4" />
				<span>Resources & Guides</span>
			</div>
			<h1 class="text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl">
				Resources & <span class="text-primary-main">Guides</span>
			</h1>
			<p class="mt-6 text-lg leading-relaxed text-gray-300">
				A curated collection of learning resources, external tools, and helpful guides to enhance
				your Elite Dangerous experience as part of IGFV.
			</p>
		</div>
	</div>
</section>

<!-- Learning Resources -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			Learning <span class="text-primary-main">Resources</span>
		</h2>
	</div>
	<div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
		<div use:inview={{ delay: 100 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<CompassSolid class="h-5 w-5" />
				</div>
				<h3 class="mb-3 text-lg font-bold text-white">Exploration Guide</h3>
				<ul class="space-y-2 text-sm text-gray-400">
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Recommended exploration
						ship builds (Asp Explorer, Krait Phantom, Anaconda)
					</li>
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Full Spectrum System
						Scanner (FSS) and Detailed Surface Scanner (DSS) usage
					</li>
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Neutron star and
						white dwarf boosting techniques
					</li>
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Exploration data
						selling and first discovery bonuses
					</li>
				</ul>
			</div>
		</div>
		<div use:inview={{ delay: 150 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<HammerSolid class="h-5 w-5" />
				</div>
				<h3 class="mb-3 text-lg font-bold text-white">BGS Operations Guide</h3>
				<ul class="space-y-2 text-sm text-gray-400">
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Understanding the
						Background Simulation and faction influence
					</li>
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Influence mechanics:
						trade, missions, exploration, and combat
					</li>
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Conflict zone tactics
						and war/retreat mechanics
					</li>
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Using Inara and
						EDDB to track faction influence
					</li>
				</ul>
			</div>
		</div>
		<div use:inview={{ delay: 200 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<ToolboxSolid class="h-5 w-5" />
				</div>
				<h3 class="mb-3 text-lg font-bold text-white">Engineering & Crafting</h3>
				<ul class="space-y-2 text-sm text-gray-400">
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Engineer unlock
						requirements and locations
					</li>
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Material farming:
						encoded, manufactured, and raw materials
					</li>
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Ship optimization:
						balancing speed, jump range, and combat capability
					</li>
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Recommended loadouts
						for different playstyles
					</li>
				</ul>
			</div>
		</div>
		<div use:inview={{ delay: 250 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<FireSolid class="h-5 w-5" />
				</div>
				<h3 class="mb-3 text-lg font-bold text-white">Trading & Mining</h3>
				<ul class="space-y-2 text-sm text-gray-400">
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Profitable trade
						route planning with Inara and EDDB
					</li>
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Core mining vs.
						laser mining: techniques and equipment
					</li>
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Best mining locations
						and current market prices
					</li>
					<li class="flex items-start gap-2">
						<CheckSolid class="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-primary-main" /> Fleet carrier trading:
						buy low, sell high strategy
					</li>
				</ul>
			</div>
		</div>
	</div>
</section>

<!-- External Tools & Databases -->
<section
	class="border-t border-primary-main/20 bg-gradient-to-b from-dark-bg via-primary-main/5 to-dark-bg"
>
	<div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
		<div use:inview class="inview-hidden">
			<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
				External Tools & <span class="text-primary-main">Databases</span>
			</h2>
		</div>
		<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
			<div use:inview={{ delay: 100 }} class="inview-hidden group">
				<a
					href="https://inara.cz"
					target="_blank"
					rel="noopener noreferrer"
					class="bg-dark/50 block h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
					>
						<GlobeAmericasSolid class="h-5 w-5" />
					</div>
					<h3 class="mb-2 text-lg font-bold text-white">Inara</h3>
					<p class="text-sm text-gray-400">
						The essential Elite Dangerous companion. Track squadron stats, find trade routes, check
						commodity prices, and manage your CMDR profile.
					</p>
					<div class="mt-4 flex items-center gap-1 text-xs text-primary-light">
						<span>Visit Inara</span>
						<ExternalLinkAltSolid class="h-3 w-3" />
					</div>
				</a>
			</div>
			<div use:inview={{ delay: 150 }} class="inview-hidden group">
				<a
					href="https://eddb.io"
					target="_blank"
					rel="noopener noreferrer"
					class="bg-dark/50 block h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
					>
						<GlobeAmericasSolid class="h-5 w-5" />
					</div>
					<h3 class="mb-2 text-lg font-bold text-white">EDDB</h3>
					<p class="text-sm text-gray-400">
						The Elite Dangerous Database. Find stations, systems, commodities, and shipyard
						information across the galaxy.
					</p>
					<div class="mt-4 flex items-center gap-1 text-xs text-primary-light">
						<span>Visit EDDB</span>
						<ExternalLinkAltSolid class="h-3 w-3" />
					</div>
				</a>
			</div>
			<div use:inview={{ delay: 200 }} class="inview-hidden group">
				<a
					href="https://edsy.page"
					target="_blank"
					rel="noopener noreferrer"
					class="bg-dark/50 block h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
					>
						<FireSolid class="h-5 w-5" />
					</div>
					<h3 class="mb-2 text-lg font-bold text-white">EDSY</h3>
					<p class="text-sm text-gray-400">
						Advanced ship outfitting and engineering planner. Design, optimize, and share ship
						builds.
					</p>
					<div class="mt-4 flex items-center gap-1 text-xs text-primary-light">
						<span>Visit EDSY</span>
						<ExternalLinkAltSolid class="h-3 w-3" />
					</div>
				</a>
			</div>
			<div use:inview={{ delay: 250 }} class="inview-hidden group">
				<a
					href="https://canonn.science"
					target="_blank"
					rel="noopener noreferrer"
					class="bg-dark/50 block h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
					>
						<StarSolid class="h-5 w-5" />
					</div>
					<h3 class="mb-2 text-lg font-bold text-white">Canonn Research</h3>
					<p class="text-sm text-gray-400">
						Research network dedicated to uncovering the mysteries of the Elite Dangerous galaxy
						through scientific investigation.
					</p>
					<div class="mt-4 flex items-center gap-1 text-xs text-primary-light">
						<span>Visit Canonn</span>
						<ExternalLinkAltSolid class="h-3 w-3" />
					</div>
				</a>
			</div>
		</div>
	</div>
</section>

<!-- Need Help? -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			Need <span class="text-primary-main">Help</span>?
		</h2>
	</div>
	<div class="grid grid-cols-1 gap-6 md:grid-cols-3">
		<div use:inview={{ delay: 100 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<QuestionCircleSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Ask on Discord</h3>
				<p class="text-sm text-gray-400">
					Our community is always ready to help. Post your questions in the <span
						class="font-medium text-primary-light">#help</span
					> channel and you'll get answers quickly.
				</p>
			</div>
		</div>
		<div use:inview={{ delay: 200 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<BookSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">Read the Guides</h3>
				<p class="text-sm text-gray-400">
					Check our community guides section for in-depth tutorials on exploration, BGS,
					engineering, and more.
				</p>
			</div>
		</div>
		<div use:inview={{ delay: 300 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
				>
					<RocketSolid class="h-6 w-6" />
				</div>
				<h3 class="mb-2 text-lg font-bold text-white">One-on-One Mentorship</h3>
				<p class="text-sm text-gray-400">
					New to the game? Request a mentor and get personalized guidance from experienced
					commanders.
				</p>
			</div>
		</div>
	</div>
	<div use:inview={{ delay: 200 }} class="inview-hidden mt-8">
		<div class="rounded-lg border border-amber-500/30 bg-amber-500/5 p-6 backdrop-blur-sm">
			<div class="flex items-start gap-3">
				<StarSolid class="mt-0.5 h-5 w-5 flex-shrink-0 text-amber-400" />
				<div>
					<h3 class="font-semibold text-white">Pro Tip</h3>
					<p class="mt-1 text-sm text-gray-400">
						Bookmark the <a
							href="https://elite-dangerous.fandom.com/"
							target="_blank"
							rel="noopener noreferrer"
							class="text-primary-light hover:underline">Elite Dangerous Wiki</a
						>
						and the
						<a
							href="https://forums.frontier.co.uk/"
							target="_blank"
							rel="noopener noreferrer"
							class="text-primary-light hover:underline">official forums</a
						>—they're invaluable resources for both new and veteran commanders. Also, don't forget
						to join the <span class="font-medium text-primary-light">#help</span> channel on our Discord
						for real-time assistance.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>

// src/app/resources/page.tsx
'use client';

import { FaBook, FaRocket, FaToolbox, FaChartLine, FaShoppingCart, FaExternalLinkAlt } from 'react-icons/fa';
import { motion } from 'framer-motion';

export default function ResourcesPage() {
  const categories = [
    {
      icon: FaRocket,
      title: 'Ship Builds & Progression',
      description: 'Starter ships to endgame builds',
      items: [
        'Cobra Mk3 → Python → Anaconda progression',
        'Exploration ships: DBX, AspX, Anaconda',
        'Mining setups: Python, Cutter, Type-10',
        'Combat builds: Vulture, Chieftain, Vette',
        'Trading: Python, T9, Cutter',
      ],
    },
    {
      icon: FaToolbox,
      title: 'Engineering & Materials',
      description: 'Maximize your ship performance',
      items: [
        'G5 engineering priorities by role',
        'Material farming locations',
        'Blueprint efficiency guide',
        'Engineer unlock requirements',
        'Experimental effects explained',
      ],
    },
    {
      icon: FaChartLine,
      title: 'Trading & Economy',
      description: 'Profit-making guide',
      items: [
        'High-profit trade routes',
        'Commodity market analysis',
        'Station types and benefits',
        'BGS influence mechanics',
        'Market data resources (EDDB, Inara)',
      ],
    },
    {
      icon: FaShoppingCart,
      title: 'Mining & Resources',
      description: 'Resource gathering strategies',
      items: [
        'Pristine metallic ring locations',
        'Laser vs core mining comparison',
        'Material values and demand',
        'LTD vs platinum profit analysis',
        'Mining hotspot guide',
      ],
    },
  ];

  const externalResources = [
    {
      name: 'EDDB (Elite Dangerous Database)',
      url: 'https://eddb.io',
      description: 'Station data, trade routes, commodities',
    },
    {
      name: 'Inara.Cz',
      url: 'https://inara.cz',
      description: 'Commander profiles, squadron stats, FC registry',
    },
    {
      name: 'EDSM (Elite Dangerous Star Map)',
      url: 'https://edsm.net',
      description: 'Exploration data, system information',
    },
    {
      name: 'Coriolis.io',
      url: 'https://coriolis.io',
      description: 'Ship builder and cost calculator',
    },
  ];

  return (
    <div className="min-h-screen py-12">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Page Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="mb-12"
        >
          <div className="bg-gradient-to-r from-norway-red/20 to-norway-blue/20 border border-norway-red/30 rounded-lg p-8 md:p-12">
            <div className="flex items-center gap-4 mb-4">
              <FaBook className="text-4xl md:text-5xl text-norway-red" />
              <h1 className="text-4xl md:text-5xl font-bold text-white">Resources & Guides</h1>
            </div>
            <p className="text-lg text-gray-300">Community-curated guides for ship building, engineering, trading, and exploration.</p>
          </div>
        </motion.div>

        {/* Resource Categories */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="mb-16"
        >
          <h2 className="text-3xl font-bold text-white mb-8">Learning Resources</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {categories.map((cat, idx) => {
              const Icon = cat.icon;
              return (
                <motion.div
                  key={idx}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.4, delay: 0.05 * idx }}
                  className="bg-dark/50 backdrop-blur-sm rounded-lg overflow-hidden shadow-glow border border-norway-red/20"
                >
                  <div className="bg-gradient-to-r from-norway-red/20 to-transparent p-6 border-b border-norway-red/20">
                    <div className="flex items-center gap-3 mb-2">
                      <Icon className="text-norway-red text-2xl" />
                      <h3 className="text-xl font-bold text-white">{cat.title}</h3>
                    </div>
                    <p className="text-gray-400 text-sm">{cat.description}</p>
                  </div>
                  <div className="p-6">
                    <ul className="space-y-2">
                      {cat.items.map((item, i) => (
                        <li key={i} className="flex items-start gap-2 text-gray-300 text-sm">
                          <span className="text-norway-red flex-shrink-0 mt-1">•</span>
                          <span>{item}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </motion.div>
              );
            })}
          </div>
        </motion.div>

        {/* External Resources */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mb-12"
        >
          <h2 className="text-3xl font-bold text-white mb-8">External Tools & Databases</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {externalResources.map((resource, idx) => (
              <motion.a
                key={idx}
                href={resource.url}
                target="_blank"
                rel="noopener noreferrer"
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.4, delay: 0.05 * idx }}
                className="bg-dark/50 backdrop-blur-sm rounded-lg p-6 shadow-glow hover:shadow-glow-hover transition-all border border-norway-blue/20 hover:border-norway-blue/60 cursor-pointer group"
              >
                <div className="flex items-start justify-between mb-3">
                  <h3 className="text-lg font-bold text-white group-hover:text-norway-red transition-colors">{resource.name}</h3>
                  <FaExternalLinkAlt className="text-norway-red flex-shrink-0 opacity-0 group-hover:opacity-100 transition-opacity" />
                </div>
                <p className="text-gray-400">{resource.description}</p>
              </motion.a>
            ))}
          </div>
        </motion.div>

        {/* Getting Help */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="bg-dark/50 backdrop-blur-sm rounded-lg p-8 shadow-glow border border-norway-red/20"
        >
          <h2 className="text-2xl font-bold text-white mb-6">Need Help?</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
              <h3 className="text-white font-bold mb-2">Discord #guides</h3>
              <p className="text-gray-400 text-sm">Ask questions and get real-time help from experienced pilots.</p>
            </div>
            <div>
              <h3 className="text-white font-bold mb-2">Community Builds</h3>
              <p className="text-gray-400 text-sm">Check Discord pins for curated ship builds and loadouts.</p>
            </div>
            <div>
              <h3 className="text-white font-bold mb-2">Mentor Program</h3>
              <p className="text-gray-400 text-sm">New commanders can request mentors in #recruitment channel.</p>
            </div>
          </div>
          <div className="mt-6 p-4 bg-norway-blue/10 rounded-lg border border-norway-blue/30">
            <p className="text-gray-300 text-sm">
              💡 <strong>Pro Tip:</strong> Most resources are maintained on our Discord server. Check pinned messages in each channel for the latest guides!
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
