// src/routes/partners/+page.svelte
<script lang="ts">
	import { inview } from '$lib/actions/inview';
	import {
		HandshakeSolid,
		StarSolid,
		GlobeAmericasSolid,
		DiscordBrands,
		CalendarAltSolid,
		FireSolid
	} from 'svelte-awesome-icons';
</script>

<!-- Hero Section -->
<section class="relative overflow-hidden border-b border-primary-main/20">
	<div
		class="absolute inset-0 bg-gradient-to-b from-primary-main/5 via-transparent to-transparent"
	></div>
	<div class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-32">
		<div use:inview class="inview-hidden mx-auto max-w-3xl text-center">
			<div
				class="mb-6 inline-flex items-center gap-2 rounded-full border border-primary-main/30 bg-primary-main/10 px-4 py-1.5 text-sm text-primary-light"
			>
				<HandshakeSolid class="h-4 w-4" />
				<span>Partners</span>
			</div>
			<h1 class="text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl">
				Squadron <span class="text-primary-main">Partners</span>
			</h1>
			<p class="mt-6 text-lg leading-relaxed text-gray-300">
				IGFV is proud to collaborate with fellow squadrons and organizations across the galaxy.
				Together, we build a stronger, more vibrant community.
			</p>
		</div>
	</div>
</section>

<!-- Squadron Partners -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			Squadron <span class="text-primary-main">Partners</span>
		</h2>
	</div>
	<div class="space-y-6">
		<div use:inview={{ delay: 100 }} class="inview-hidden group">
			<div
				class="bg-dark/50 rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div class="grid grid-cols-1 gap-6 md:grid-cols-4">
					<div class="flex items-center gap-3 md:col-span-1">
						<div
							class="flex h-14 w-14 items-center justify-center rounded-lg bg-primary-main/20 text-2xl font-bold text-primary-light"
						>
							NOVA
						</div>
						<div>
							<h3 class="text-lg font-bold text-white">Nova Legion</h3>
							<div
								class="inline-block rounded-full bg-primary-main/10 px-2.5 py-0.5 text-xs font-medium text-primary-light"
							>
								Squadron
							</div>
						</div>
					</div>
					<div class="md:col-span-2">
						<p class="text-sm text-gray-400">
							A kindred spirit in exploration and community-building. Nova Legion shares our passion
							for discovery and peaceful coexistence in the galaxy. Regular joint expeditions and
							shared BGS intelligence.
						</p>
					</div>
					<div class="flex flex-col gap-2 md:col-span-1 md:items-end">
						<div class="text-xs text-gray-500">
							<p class="flex items-center gap-1">
								<FireSolid class="h-3 w-3 text-primary-main" /> Specialty: Exploration
							</p>
							<p class="flex items-center gap-1">
								<CalendarAltSolid class="h-3 w-3 text-primary-main" /> 3 joint events
							</p>
						</div>
						<a
							href="https://discord.gg/partner1"
							target="_blank"
							rel="noopener noreferrer"
							class="inline-flex items-center gap-1.5 text-xs text-primary-light transition-colors hover:text-primary-main"
						>
							<DiscordBrands class="h-3 w-3" /> Connect
						</a>
					</div>
				</div>
			</div>
		</div>
		<div use:inview={{ delay: 150 }} class="inview-hidden group">
			<div
				class="bg-dark/50 rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div class="grid grid-cols-1 gap-6 md:grid-cols-4">
					<div class="flex items-center gap-3 md:col-span-1">
						<div
							class="flex h-14 w-14 items-center justify-center rounded-lg bg-primary-main/20 text-2xl font-bold text-primary-light"
						>
							DSN
						</div>
						<div>
							<h3 class="text-lg font-bold text-white">Deep Space Network</h3>
							<div
								class="inline-block rounded-full bg-primary-main/10 px-2.5 py-0.5 text-xs font-medium text-primary-light"
							>
								Squadron
							</div>
						</div>
					</div>
					<div class="md:col-span-2">
						<p class="text-sm text-gray-400">
							A network of explorers dedicated to mapping the galaxy. Deep Space Network shares
							exploration data and coordinates long-range expeditions with IGFV.
						</p>
					</div>
					<div class="flex flex-col gap-2 md:col-span-1 md:items-end">
						<div class="text-xs text-gray-500">
							<p class="flex items-center gap-1">
								<FireSolid class="h-3 w-3 text-primary-main" /> Specialty: Data sharing
							</p>
							<p class="flex items-center gap-1">
								<CalendarAltSolid class="h-3 w-3 text-primary-main" /> 5 joint events
							</p>
						</div>
						<a
							href="https://discord.gg/partner2"
							target="_blank"
							rel="noopener noreferrer"
							class="inline-flex items-center gap-1.5 text-xs text-primary-light transition-colors hover:text-primary-main"
						>
							<DiscordBrands class="h-3 w-3" /> Connect
						</a>
					</div>
				</div>
			</div>
		</div>
		<div use:inview={{ delay: 200 }} class="inview-hidden group">
			<div
				class="bg-dark/50 rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div class="grid grid-cols-1 gap-6 md:grid-cols-4">
					<div class="flex items-center gap-3 md:col-span-1">
						<div
							class="flex h-14 w-14 items-center justify-center rounded-lg bg-primary-main/20 text-2xl font-bold text-primary-light"
						>
							TFD
						</div>
						<div>
							<h3 class="text-lg font-bold text-white">The Fuel Rats</h3>
							<div
								class="inline-block rounded-full bg-primary-main/10 px-2.5 py-0.5 text-xs font-medium text-primary-light"
							>
								Squadron
							</div>
						</div>
					</div>
					<div class="md:col-span-2">
						<p class="text-sm text-gray-400">
							The galaxy's premier emergency refueling service. The Fuel Rats provide critical
							support to commanders in need, and we're proud to have members who serve alongside
							them.
						</p>
					</div>
					<div class="flex flex-col gap-2 md:col-span-1 md:items-end">
						<div class="text-xs text-gray-500">
							<p class="flex items-center gap-1">
								<FireSolid class="h-3 w-3 text-primary-main" /> Specialty: Rescue ops
							</p>
							<p class="flex items-center gap-1">
								<CalendarAltSolid class="h-3 w-3 text-primary-main" /> Ongoing support
							</p>
						</div>
						<a
							href="https://discord.gg/partner3"
							target="_blank"
							rel="noopener noreferrer"
							class="inline-flex items-center gap-1.5 text-xs text-primary-light transition-colors hover:text-primary-main"
						>
							<DiscordBrands class="h-3 w-3" /> Connect
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Supporting Partners -->
<section
	class="border-t border-primary-main/20 bg-gradient-to-b from-dark-bg via-primary-main/5 to-dark-bg"
>
	<div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
		<div use:inview class="inview-hidden">
			<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
				Supporting <span class="text-primary-main">Partners</span>
			</h2>
		</div>
		<div class="grid grid-cols-1 gap-6 md:grid-cols-3">
			<div use:inview={{ delay: 100 }} class="inview-hidden group">
				<div
					class="bg-dark/50 rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-primary-main/10"
					>
						<GlobeAmericasSolid class="h-8 w-8 text-primary-main/60" />
					</div>
					<h3 class="mb-1 text-lg font-bold text-white">Elite Dangerous Community</h3>
					<p class="text-xs text-gray-500">Supporting Partner</p>
					<p class="mt-2 text-sm text-gray-400">
						The official Elite Dangerous community forums and resources.
					</p>
				</div>
			</div>
			<div use:inview={{ delay: 200 }} class="inview-hidden group">
				<div
					class="bg-dark/50 rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-primary-main/10"
					>
						<StarSolid class="h-8 w-8 text-primary-main/60" />
					</div>
					<h3 class="mb-1 text-lg font-bold text-white">Inara</h3>
					<p class="text-xs text-gray-500">Supporting Partner</p>
					<p class="mt-2 text-sm text-gray-400">
						The leading Elite Dangerous companion database and social platform.
					</p>
				</div>
			</div>
			<div use:inview={{ delay: 300 }} class="inview-hidden group">
				<div
					class="bg-dark/50 rounded-lg border border-primary-main/30 p-6 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div
						class="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-primary-main/10"
					>
						<FireSolid class="h-8 w-8 text-primary-main/60" />
					</div>
					<h3 class="mb-1 text-lg font-bold text-white">Canonn Research</h3>
					<p class="text-xs text-gray-500">Supporting Partner</p>
					<p class="mt-2 text-sm text-gray-400">
						Scientific research network uncovering the mysteries of the galaxy.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Become a Partner CTA -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
	<div use:inview class="inview-hidden">
		<div
			class="to-dark/50 rounded-lg border border-primary-main/30 bg-gradient-to-br from-primary-main/10 p-8 text-center shadow-glow backdrop-blur-sm sm:p-12"
		>
			<h2 class="text-3xl font-bold text-white sm:text-4xl">
				Become a <span class="text-primary-main">Partner</span>
			</h2>
			<p class="mx-auto mt-4 max-w-2xl text-gray-300">
				Interested in partnering with IGFV? We're always open to collaborations with like-minded
				squadrons and organizations. Reach out to us on Discord to discuss partnership
				opportunities.
			</p>
			<a
				href="https://discord.gg/igfv"
				target="_blank"
				rel="noopener noreferrer"
				class="mt-6 inline-flex items-center gap-2 rounded-lg bg-primary-main px-8 py-3 font-semibold text-white transition-all duration-300 hover:bg-primary-light hover:shadow-glow-hover"
			>
				<HandshakeSolid class="h-5 w-5" />
				Contact Us
			</a>
		</div>
	</div>
</section>

// src/app/partners/page.tsx
'use client';

import { motion } from 'framer-motion';
import { FaHandshake, FaGamepad, FaBriefcase, FaUsers, FaRocket, FaShieldAlt } from 'react-icons/fa';
import { RiSpaceShipFill } from 'react-icons/ri';

interface Partner {
  name: string;
  description: string;
  specialty: string;
  events?: string[];
  website?: string;
  discord?: string;
}

const squadronPartners: Partner[] = [
  {
    name: 'Example Squadron Alpha',
    description: 'A veteran squadron focused on exploration and deep space discovery.',
    specialty: 'Exploration & Cartography',
    events: [
      'Joint Expedition to Colonia (2024)',
      'Guardian Site Survey Mission (2023)',
    ],
    discord: 'https://discord.gg/example',
  },
  {
    name: 'Example Squadron Beta',
    description: 'Combat-oriented squadron specializing in anti-Thargoid operations.',
    specialty: 'Combat & AX Operations',
    events: [
      'Thargoid Defense Initiative (2024)',
      'Wing Combat Training Program',
    ],
    discord: 'https://discord.gg/example',
  },
  {
    name: 'Example Squadron Gamma',
    description: 'Trading and mining focused group supporting the galactic economy.',
    specialty: 'Trade & Mining',
    events: [
      'Community Mining Event (2024)',
      'Trade Route Establishment Program',
    ],
    discord: 'https://discord.gg/example',
  },
];

const nonGamePartners: Partner[] = [
  {
    name: 'Example Tech Partner',
    description: 'Providing server infrastructure and technical support for our community.',
    specialty: 'Technology & Infrastructure',
    website: 'https://example.com',
  },
  {
    name: 'Example Content Creator',
    description: 'Content creation and community engagement partner.',
    specialty: 'Media & Content',
    website: 'https://example.com',
  },
];

function PartnerCard({ partner, icon }: { partner: Partner; icon: React.ReactNode }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.5 }}
      className="bg-dark/50 backdrop-blur-sm border border-primary-main/20 rounded-lg p-6 shadow-glow hover:shadow-glow-hover hover:border-primary-main/60 transition-all group"
    >
      <div className="flex items-start gap-4 mb-4">
        <div className="text-primary-main group-hover:text-white text-3xl flex-shrink-0 transition-colors">
          {icon}
        </div>
        <div>
          <h3 className="text-xl font-bold text-white mb-2">{partner.name}</h3>
          <p className="text-gray-400 text-sm mb-2">{partner.description}</p>
        </div>
      </div>
      
      <div className="mb-4">
        <span className="inline-block bg-primary-main/20 border border-primary-main/40 text-primary-light px-3 py-1 rounded-full text-sm font-semibold">
          {partner.specialty}
        </span>
      </div>

      {partner.events && partner.events.length > 0 && (
        <div className="mb-4">
          <h4 className="text-sm font-semibold text-primary-light mb-2">Collaborated Events:</h4>
          <ul className="space-y-1">
            {partner.events.map((event, index) => (
              <li key={index} className="text-gray-400 text-sm flex items-start">
                <span className="text-primary-main mr-2">•</span>
                {event}
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="flex gap-3 mt-4">
        {partner.discord && (
          <a
            href={partner.discord}
            target="_blank"
            rel="noopener noreferrer"
            className="px-4 py-2 bg-primary-main/20 hover:bg-primary-main text-white rounded-md text-sm font-semibold transition-colors"
          >
            Discord
          </a>
        )}
        {partner.website && (
          <a
            href={partner.website}
            target="_blank"
            rel="noopener noreferrer"
            className="px-4 py-2 bg-primary-main/20 hover:bg-primary-main text-white rounded-md text-sm font-semibold transition-colors"
          >
            Website
          </a>
        )}
      </div>
    </motion.div>
  );
}

export default function PartnersPage() {
  return (
    <div className="min-h-screen py-16 px-4 pt-28">
      <div className="container mx-auto max-w-6xl">
        {/* Hero Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <div className="flex justify-center items-center gap-4 mb-4">
            <FaHandshake className="text-5xl text-primary-main" />
          </div>
          <h1 className="text-5xl md:text-6xl font-bold text-white mb-4">
            Our Partners
          </h1>
          <p className="text-xl text-gray-400 max-w-3xl mx-auto">
            Working together with squadrons and organizations to create amazing experiences
            in Elite Dangerous and beyond.
          </p>
        </motion.div>

        {/* Squadron Partners Section */}
        <section className="mb-16">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="mb-8"
          >
            <div className="flex items-center gap-3 mb-4">
              <RiSpaceShipFill className="text-3xl text-primary-main" />
              <h2 className="text-3xl font-bold text-white">Squadron Partners</h2>
            </div>
            <p className="text-gray-400 text-lg">
              Elite Dangerous squadrons we collaborate with for events, operations, and community initiatives.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 gap-6">
            {squadronPartners.map((partner, index) => (
              <PartnerCard
                key={index}
                partner={partner}
                icon={
                  index === 0 ? <FaRocket /> :
                  index === 1 ? <FaShieldAlt /> :
                  <FaUsers />
                }
              />
            ))}
          </div>
        </section>

        {/* Non-Game Partners Section */}
        <section>
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="mb-8"
          >
            <div className="flex items-center gap-3 mb-4">
              <FaBriefcase className="text-3xl text-primary-main" />
              <h2 className="text-3xl font-bold text-white">Community Partners</h2>
            </div>
            <p className="text-gray-400 text-lg">
              Organizations and creators supporting our community infrastructure and content.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 gap-6">
            {nonGamePartners.map((partner, index) => (
              <PartnerCard
                key={index}
                partner={partner}
                icon={index === 0 ? <FaGamepad /> : <FaBriefcase />}
              />
            ))}
          </div>
        </section>

        {/* Become a Partner CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="mt-16 text-center bg-dark/50 backdrop-blur-sm border border-primary-main/20 rounded-lg p-8 shadow-glow"
        >
          <h3 className="text-2xl font-bold text-white mb-4">Interested in Partnering?</h3>
          <p className="text-gray-400 mb-6 max-w-2xl mx-auto">
            We&apos;re always looking to collaborate with like-minded squadrons and organizations.
            Reach out to us on Discord to discuss partnership opportunities.
          </p>
          <a
            href="https://discord.gg/invite/Jvrgy6EEQn"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-block px-6 py-3 bg-primary-main hover:bg-primary-darkest text-white rounded-md font-semibold transition-colors"
          >
            Contact Us on Discord
          </a>
        </motion.div>
      </div>
    </div>
  );
}
