// src/routes/fleet-carrier/+page.svelte
<script lang="ts">
	import { inview } from '$lib/actions/inview';
	import {
		SpaceShuttleSolid,
		MapMarkerAltSolid,
		UsersSolid,
		CheckSolid,
		ClockSolid,
		FireSolid,
		ToolboxSolid,
		HammerSolid
	} from 'svelte-awesome-icons';
</script>

<!-- Hero Section -->
<section class="relative overflow-hidden border-b border-primary-main/20">
	<div
		class="absolute inset-0 bg-gradient-to-b from-primary-main/5 via-transparent to-transparent"
	></div>
	<div class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-32">
		<div use:inview class="inview-hidden mx-auto max-w-3xl text-center">
			<div
				class="mb-6 inline-flex items-center gap-2 rounded-full border border-primary-main/30 bg-primary-main/10 px-4 py-1.5 text-sm text-primary-light"
			>
				<SpaceShuttleSolid class="h-4 w-4" />
				<span>Fleet Carrier</span>
			</div>
			<h1 class="text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl">
				ISS <span class="text-primary-main">Valhall</span>
			</h1>
			<p class="mt-3 text-lg text-primary-light">VXX-RHJ</p>
			<p class="mt-4 text-lg leading-relaxed text-gray-300">
				Our mobile headquarters and home away from home. The ISS Valhall serves as the central hub
				for all IGFV operations, providing essential services and a safe harbor for our commanders.
			</p>
		</div>
	</div>
</section>

<!-- Location & Carrier Info -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			Current <span class="text-primary-main">Status</span>
		</h2>
	</div>
	<div class="grid grid-cols-1 gap-6 md:grid-cols-2">
		<div use:inview={{ delay: 100 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div class="mb-4 flex items-center gap-3">
					<div
						class="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
					>
						<MapMarkerAltSolid class="h-5 w-5" />
					</div>
					<h3 class="text-lg font-bold text-white">Current Location</h3>
				</div>
				<div class="space-y-3 text-sm">
					<div class="flex items-center justify-between border-b border-primary-main/10 pb-2">
						<span class="text-gray-400">System</span>
						<span class="font-medium text-white">Shinrarta Dezhra</span>
					</div>
					<div class="flex items-center justify-between border-b border-primary-main/10 pb-2">
						<span class="text-gray-400">Body</span>
						<span class="font-medium text-white">Jameson Memorial</span>
					</div>
					<div class="flex items-center justify-between border-b border-primary-main/10 pb-2">
						<span class="text-gray-400">Population</span>
						<span class="font-medium text-white">38,000,000+</span>
					</div>
					<div class="flex items-center justify-between">
						<span class="text-gray-400">Allegiance</span>
						<span class="font-medium text-white">Independent</span>
					</div>
				</div>
			</div>
		</div>
		<div use:inview={{ delay: 200 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div class="mb-4 flex items-center gap-3">
					<div
						class="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
					>
						<SpaceShuttleSolid class="h-5 w-5" />
					</div>
					<h3 class="text-lg font-bold text-white">Carrier Information</h3>
				</div>
				<div class="space-y-3 text-sm">
					<div class="flex items-center justify-between border-b border-primary-main/10 pb-2">
						<span class="text-gray-400">Name</span>
						<span class="font-medium text-white">ISS Valhall</span>
					</div>
					<div class="flex items-center justify-between border-b border-primary-main/10 pb-2">
						<span class="text-gray-400">Callsign</span>
						<span class="font-medium text-white">VXX-RHJ</span>
					</div>
					<div class="flex items-center justify-between border-b border-primary-main/10 pb-2">
						<span class="text-gray-400">Class</span>
						<span class="font-medium text-white">Majestic-Class Fleet Carrier</span>
					</div>
					<div class="flex items-center justify-between border-b border-primary-main/10 pb-2">
						<span class="text-gray-400">Crew Capacity</span>
						<span class="font-medium text-white">1,000+</span>
					</div>
					<div class="flex items-center justify-between">
						<span class="text-gray-400">Max Jump Range</span>
						<span class="font-medium text-white">500 LY</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Available Services -->
<section
	class="border-t border-primary-main/20 bg-gradient-to-b from-dark-bg via-primary-main/5 to-dark-bg"
>
	<div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
		<div use:inview class="inview-hidden">
			<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
				Available <span class="text-primary-main">Services</span>
			</h2>
		</div>
		<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
			<div use:inview={{ delay: 100 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div class="mb-4 flex items-center justify-between">
						<div
							class="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
						>
							<ToolboxSolid class="h-5 w-5" />
						</div>
						<div
							class="inline-flex items-center gap-1 rounded-full bg-green-500/10 px-2.5 py-0.5 text-xs font-medium text-green-400"
						>
							<span class="h-1.5 w-1.5 rounded-full bg-green-400"></span>
							Active
						</div>
					</div>
					<h3 class="mb-2 text-lg font-bold text-white">Commodity Market</h3>
					<p class="text-sm text-gray-400">
						Buy and sell goods directly from the carrier's market. Stock varies based on location
						and recent trade activities.
					</p>
				</div>
			</div>
			<div use:inview={{ delay: 200 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div class="mb-4 flex items-center justify-between">
						<div
							class="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
						>
							<UsersSolid class="h-5 w-5" />
						</div>
						<div
							class="inline-flex items-center gap-1 rounded-full bg-green-500/10 px-2.5 py-0.5 text-xs font-medium text-green-400"
						>
							<span class="h-1.5 w-1.5 rounded-full bg-green-400"></span>
							Active
						</div>
					</div>
					<h3 class="mb-2 text-lg font-bold text-white">Crew Quarters</h3>
					<p class="text-sm text-gray-400">
						Rest and relax between expeditions. Full crew facilities available for all squadron
						members.
					</p>
				</div>
			</div>
			<div use:inview={{ delay: 300 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div class="mb-4 flex items-center justify-between">
						<div
							class="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
						>
							<HammerSolid class="h-5 w-5" />
						</div>
						<div
							class="inline-flex items-center gap-1 rounded-full bg-green-500/10 px-2.5 py-0.5 text-xs font-medium text-green-400"
						>
							<span class="h-1.5 w-1.5 rounded-full bg-green-400"></span>
							Active
						</div>
					</div>
					<h3 class="mb-2 text-lg font-bold text-white">Repair & Rearm</h3>
					<p class="text-sm text-gray-400">
						Full repair, restock, and rearming services available. Get your ship battle-ready before
						heading out.
					</p>
				</div>
			</div>
			<div use:inview={{ delay: 400 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div class="mb-4 flex items-center justify-between">
						<div
							class="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-main/20 text-primary-light"
						>
							<FireSolid class="h-5 w-5" />
						</div>
						<div
							class="inline-flex items-center gap-1 rounded-full bg-green-500/10 px-2.5 py-0.5 text-xs font-medium text-green-400"
						>
							<span class="h-1.5 w-1.5 rounded-full bg-green-400"></span>
							Active
						</div>
					</div>
					<h3 class="mb-2 text-lg font-bold text-white">Fuel Depot</h3>
					<p class="text-sm text-gray-400">
						Refuel your ship and the carrier's own fuel reserves. Essential for long-range
						exploration operations.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Upcoming Jumps -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			Upcoming <span class="text-primary-main">Jumps</span>
		</h2>
	</div>
	<div class="mx-auto grid max-w-4xl grid-cols-1 gap-6 md:grid-cols-3">
		<div use:inview={{ delay: 100 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div class="mb-3 flex items-center gap-2">
					<ClockSolid class="h-4 w-4 text-primary-main" />
					<span class="text-sm text-gray-400">March 20, 3311 — 14:00 IGT</span>
				</div>
				<h3 class="text-lg font-bold text-white">Jump to Colonia</h3>
				<div class="mt-3 space-y-1 text-sm text-gray-400">
					<p>Distance: ~22,000 LY</p>
					<p>Stops: 8 waypoints</p>
					<p>Duration: ~2 weeks</p>
				</div>
			</div>
		</div>
		<div use:inview={{ delay: 200 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div class="mb-3 flex items-center gap-2">
					<ClockSolid class="h-4 w-4 text-primary-main" />
					<span class="text-sm text-gray-400">April 5, 3311 — 10:00 IGT</span>
				</div>
				<h3 class="text-lg font-bold text-white">Return to Bubble</h3>
				<div class="mt-3 space-y-1 text-sm text-gray-400">
					<p>Destination: Sol</p>
					<p>Stops: Direct route</p>
					<p>Duration: ~3 days</p>
				</div>
			</div>
		</div>
		<div use:inview={{ delay: 300 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div class="mb-3 flex items-center gap-2">
					<ClockSolid class="h-4 w-4 text-primary-main" />
					<span class="text-sm text-gray-400">April 20, 3311 — 08:00 IGT</span>
				</div>
				<h3 class="text-lg font-bold text-white">HIP 12345 Campaign</h3>
				<div class="mt-3 space-y-1 text-sm text-gray-400">
					<p>Destination: HIP 12345</p>
					<p>Distance: ~150 LY</p>
					<p>Duration: 1 week</p>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Rules & Guidelines -->
<section
	class="border-t border-primary-main/20 bg-gradient-to-b from-dark-bg via-primary-main/5 to-dark-bg"
>
	<div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
		<div use:inview class="inview-hidden">
			<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
				Carrier Rules & <span class="text-primary-main">Guidelines</span>
			</h2>
		</div>
		<div class="mx-auto max-w-3xl space-y-4">
			<div
				use:inview={{ delay: 100 }}
				class="inview-hidden bg-dark/50 flex items-start gap-3 rounded-lg border border-primary-main/20 p-4 backdrop-blur-sm"
			>
				<CheckSolid class="mt-0.5 h-5 w-5 flex-shrink-0 text-green-400" />
				<div>
					<h4 class="font-medium text-white">Parking</h4>
					<p class="text-sm text-gray-400">
						Please use designated landing pads. Large ships should use the outer landing pads to
						leave room for smaller vessels.
					</p>
				</div>
			</div>
			<div
				use:inview={{ delay: 150 }}
				class="inview-hidden bg-dark/50 flex items-start gap-3 rounded-lg border border-primary-main/20 p-4 backdrop-blur-sm"
			>
				<CheckSolid class="mt-0.5 h-5 w-5 flex-shrink-0 text-green-400" />
				<div>
					<h4 class="font-medium text-white">Cargo Storage</h4>
					<p class="text-sm text-gray-400">
						Do not store illegal or prohibited goods on the carrier without prior authorization.
					</p>
				</div>
			</div>
			<div
				use:inview={{ delay: 200 }}
				class="inview-hidden bg-dark/50 flex items-start gap-3 rounded-lg border border-primary-main/20 p-4 backdrop-blur-sm"
			>
				<CheckSolid class="mt-0.5 h-5 w-5 flex-shrink-0 text-green-400" />
				<div>
					<h4 class="font-medium text-white">Jump Notifications</h4>
					<p class="text-sm text-gray-400">
						Always check the schedule before logging out. If the carrier is jumping, make sure
						you're aboard or aware of the departure time.
					</p>
				</div>
			</div>
			<div
				use:inview={{ delay: 250 }}
				class="inview-hidden bg-dark/50 flex items-start gap-3 rounded-lg border border-primary-main/20 p-4 backdrop-blur-sm"
			>
				<CheckSolid class="mt-0.5 h-5 w-5 flex-shrink-0 text-green-400" />
				<div>
					<h4 class="font-medium text-white">Respect the Crew</h4>
					<p class="text-sm text-gray-400">
						Treat the carrier crew and fellow commanders with respect at all times.
					</p>
				</div>
			</div>
			<div
				use:inview={{ delay: 300 }}
				class="inview-hidden bg-dark/50 flex items-start gap-3 rounded-lg border border-primary-main/20 p-4 backdrop-blur-sm"
			>
				<CheckSolid class="mt-0.5 h-5 w-5 flex-shrink-0 text-green-400" />
				<div>
					<h4 class="font-medium text-white">Report Issues</h4>
					<p class="text-sm text-gray-400">
						Report any technical issues or problems to squadron leadership immediately.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>

// src/app/fleet-carrier/page.tsx
'use client';

import { FaSpaceShuttle, FaMapMarkerAlt, FaClock, FaShoppingCart, FaUsers, FaExternalLinkAlt } from 'react-icons/fa';
import { motion } from 'framer-motion';
import Link from 'next/link';

export default function FleetCarrierPage() {
  // Fleet Carrier data
  const carrier = {
    name: 'Valhall',
    callsign: 'Goodfellas Valhall',
    type: 'Drake-Class',
    systemName: 'Waungaze',
    bodyName: 'Waungaze A 3 A',
    coordinates: { x: -1, y: 2, z: 3 }, // Placeholder
    ownerCmdr: 'Skalfinn',
    population: 45000,
    inaraUrl: 'https://inara.cz/cmdr-fleet-carrier/9569',
  };

  const services = [
    {
      icon: FaShoppingCart,
      title: 'Commodity Market',
      description: 'Buy and sell commodities. Check current stock before trading.',
      status: 'Active',
    },
    {
      icon: FaUsers,
      title: 'Crew Quarters',
      description: 'Housing for 100+ crew members. Comfortable accommodations for long voyages.',
      status: 'Active',
    },
    {
      icon: FaSpaceShuttle,
      title: 'Repair/Rearm',
      description: 'Full ship repair and ammunition restock. Outfitting services available.',
      status: 'Active',
    },
    {
      icon: FaClock,
      title: 'Fuel Depot',
      description: 'Fuel rats welcome. We carry fuel rammers and limpets for emergency refueling.',
      status: 'Active',
    },
  ];

  const jumpSchedule = [
    {
      date: '2025-11-15',
      destination: 'LHS 20',
      reason: 'Supply run and mining op',
      status: 'Scheduled',
    },
    {
      date: '2025-12-01',
      destination: 'Colonia',
      reason: 'Long range expedition',
      status: 'Planned',
    },
    {
      date: '2025-12-15',
      destination: 'The Void',
      reason: 'Deep space exploration',
      status: 'Planned',
    },
  ];

  return (
    <div className="min-h-screen py-12">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Hero Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="mb-12"
        >
          <div className="bg-gradient-to-r from-norway-red/20 to-norway-blue/20 border border-norway-red/30 rounded-lg p-8 md:p-12">
            <div className="flex items-center gap-4 mb-4">
              <FaSpaceShuttle className="text-4xl md:text-5xl text-norway-red" />
              <h1 className="text-4xl md:text-5xl font-bold text-white">{carrier.name}</h1>
            </div>
            <p className="text-lg text-gray-300 mb-4">{carrier.callsign}</p>
            <p className="text-gray-400">The flagship of Interstellar Goodfellas, operated by CMDR {carrier.ownerCmdr}</p>
          </div>
        </motion.div>

        {/* Quick Info Cards */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12"
        >
          {/* Location Card */}
          <div className="bg-dark/50 backdrop-blur-sm rounded-lg p-6 shadow-glow border border-norway-red/20">
            <div className="flex items-center gap-3 mb-4">
              <FaMapMarkerAlt className="text-norway-red text-2xl" />
              <h2 className="text-2xl font-bold text-white">Current Location</h2>
            </div>
            <div className="space-y-3 text-gray-300">
              <p>
                <span className="text-white font-semibold">System:</span> {carrier.systemName}
              </p>
              <p>
                <span className="text-white font-semibold">Body:</span> {carrier.bodyName}
              </p>
              <p>
                <span className="text-white font-semibold">Population:</span> {carrier.population.toLocaleString()}
              </p>
              <a
                href={carrier.inaraUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 mt-4 px-4 py-2 bg-norway-red text-white rounded-lg hover:bg-norway-red/80 transition-colors"
              >
                View on Inara <FaExternalLinkAlt className="text-sm" />
              </a>
            </div>
          </div>

          {/* Key Stats Card */}
          <div className="bg-dark/50 backdrop-blur-sm rounded-lg p-6 shadow-glow border border-norway-blue/20">
            <div className="flex items-center gap-3 mb-4">
              <FaSpaceShuttle className="text-norway-blue text-2xl" />
              <h2 className="text-2xl font-bold text-white">Carrier Info</h2>
            </div>
            <div className="space-y-3 text-gray-300">
              <p>
                <span className="text-white font-semibold">Class:</span> {carrier.type}
              </p>
              <p>
                <span className="text-white font-semibold">Crew Capacity:</span> 500+
              </p>
              <p>
                <span className="text-white font-semibold">Jump Range:</span> 500 LY per jump
              </p>
              <p className="text-sm text-gray-400 mt-4">
                ℹ️ Fleet Carriers are capital ships that serve as mobile bases for exploration,
                trading, and exploration operations.
              </p>
            </div>
          </div>
        </motion.div>

        {/* Services Section */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mb-12"
        >
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-8 flex items-center gap-3">
            <FaShoppingCart className="text-norway-red" />
            Available Services
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {services.map((service, index) => {
              const IconComponent = service.icon;
              return (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.4, delay: 0.1 * index }}
                  className="bg-dark/50 backdrop-blur-sm rounded-lg p-6 shadow-glow hover:shadow-glow-hover transition-all border border-norway-red/10"
                >
                  <div className="flex items-start gap-4 mb-3">
                    <IconComponent className="text-norway-red text-2xl flex-shrink-0 mt-1" />
                    <div className="flex-1">
                      <h3 className="text-xl font-bold text-white">{service.title}</h3>
                      <span className="inline-block mt-1 px-2 py-1 bg-green-500/20 text-green-400 text-xs font-semibold rounded">
                        {service.status}
                      </span>
                    </div>
                  </div>
                  <p className="text-gray-400">{service.description}</p>
                </motion.div>
              );
            })}
          </div>
        </motion.div>

        {/* Jump Schedule Section */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="mb-12"
        >
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-8 flex items-center gap-3">
            <FaClock className="text-norway-blue" />
            Upcoming Jumps
          </h2>
          <div className="space-y-4">
            {jumpSchedule.map((jump, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.4, delay: 0.1 * index }}
                className="bg-dark/50 backdrop-blur-sm rounded-lg p-6 shadow-glow border-l-4 border-norway-red"
              >
                <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                  <div>
                    <h3 className="text-xl font-bold text-white">{jump.destination}</h3>
                    <p className="text-gray-400 text-sm mt-1">{jump.reason}</p>
                  </div>
                  <div className="flex items-center gap-6">
                    <div className="text-right">
                      <p className="text-gray-400 text-sm">Scheduled Date</p>
                      <p className="text-white font-semibold">{new Date(jump.date).toLocaleDateString()}</p>
                    </div>
                    <span className="px-3 py-1 bg-blue-500/20 text-blue-400 text-sm font-semibold rounded whitespace-nowrap">
                      {jump.status}
                    </span>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
          <p className="text-gray-400 text-sm mt-6 p-4 bg-dark/50 rounded-lg">
            ℹ️ Jump dates are subject to change based on operational needs. Check Discord for updates.
          </p>
        </motion.div>

        {/* Rules & Guidelines Section */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="bg-dark/50 backdrop-blur-sm rounded-lg p-8 shadow-glow border border-norway-blue/20"
        >
          <h2 className="text-2xl md:text-3xl font-bold text-white mb-6">Using the Fleet Carrier</h2>
          <div className="space-y-4 text-gray-300">
            <p>
              <span className="text-norway-red font-semibold">✓ Do:</span> Contribute to squadron operations,
              participate in jump planning, respect carrier rules, coordinate with crew.
            </p>
            <p>
              <span className="text-norway-red font-semibold">✗ Don&apos;t:</span> Dock griefers, store combat ships
              in restricted bays, refuse to follow flight rules, leave the carrier without permission during
              critical operations.
            </p>
            <p className="text-sm text-gray-400 mt-6">
              Questions about the carrier? Ask the crew in{' '}
              <Link href="https://discord.gg/igfv" target="_blank" className="text-norway-red hover:underline">
                Discord #fleet-carrier
              </Link>{' '}
              channel.
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
