// src/lib/components/Header.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { BarsSolid, XmarkSolid } from 'svelte-awesome-icons';

	let mobileOpen = $state(false);

	const navLinks = [
		{ href: '/about', label: 'About' },
		{ href: '/guides', label: 'Guides' },
		{ href: '/gallery', label: 'Gallery' },
		{ href: '/partners', label: 'Partners' }
	];

	function toggleMobile() {
		mobileOpen = !mobileOpen;
	}

	function closeMobile() {
		mobileOpen = false;
	}
</script>

<header
	class="fixed top-0 right-0 left-0 z-50 border-b-4 border-primary-main bg-dark-navy shadow-lg"
>
	<div class="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
		<!-- Logo -->
		<a href="/" class="flex items-center gap-2" onclick={closeMobile}>
			<span class="text-2xl font-bold tracking-widest text-primary-main">IGFV</span>
		</a>

		<!-- Desktop Nav -->
		<nav class="hidden items-center gap-8 md:flex">
			{#each navLinks as link (link.href)}
				<a
					href={link.href}
					class="relative text-sm font-medium tracking-wider text-gray-300 uppercase transition-colors hover:text-white"
					class:active-link={$page.url.pathname === link.href}
				>
					{link.label}
					{#if $page.url.pathname === link.href}
						<span class="absolute right-0 -bottom-1 left-0 h-0.5 bg-primary-main"></span>
					{/if}
				</a>
			{/each}
			<a
				href="https://discord.gg/igfv"
				target="_blank"
				rel="noopener noreferrer"
				class="rounded-md bg-primary-main px-4 py-2 text-sm font-bold tracking-wider text-white uppercase transition-all hover:bg-primary-light hover:shadow-glow-hover"
			>
				Discord
			</a>
		</nav>

		<!-- Mobile Hamburger -->
		<button
			class="flex items-center text-gray-300 transition-colors hover:text-white md:hidden"
			onclick={toggleMobile}
			aria-label={mobileOpen ? 'Close menu' : 'Open menu'}
		>
			{#if mobileOpen}
				<XmarkSolid class="h-6 w-6" />
			{:else}
				<BarsSolid class="h-6 w-6" />
			{/if}
		</button>
	</div>

	<!-- Mobile Dropdown -->
	{#if mobileOpen}
		<div class="border-t border-dark-slate3 bg-dark-navy md:hidden">
			<nav class="flex flex-col space-y-2 px-4 py-4">
				{#each navLinks as link (link.href)}
					<a
						href={link.href}
						class="rounded px-3 py-2 text-sm font-medium tracking-wider text-gray-300 uppercase transition-colors hover:bg-dark-slate1 hover:text-white"
						class:active-link={$page.url.pathname === link.href}
						onclick={closeMobile}
					>
						{link.label}
					</a>
				{/each}
				<a
					href="https://discord.gg/igfv"
					target="_blank"
					rel="noopener noreferrer"
					class="mt-2 rounded-md bg-primary-main px-4 py-2 text-center text-sm font-bold tracking-wider text-white uppercase transition-all hover:bg-primary-light"
					onclick={closeMobile}
				>
					Discord
				</a>
			</nav>
		</div>
	{/if}
</header>

<!-- Spacer to offset fixed header -->
<div class="h-16"></div>

// src/components/Header/Header.tsx
'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline';
import { usePathname } from 'next/navigation';

export const Header: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  const pathname = usePathname();

  const navItems = [
    { href: '/about', label: 'About' },
    { href: '/guides', label: 'Guides' },
    { href: '/gallery', label: 'Gallery' },
    { href: '/partners', label: 'Partners' },
  ];

  const isActive = (href: string) => {
    if (href === '/') return pathname === '/';
    return pathname?.startsWith(href || '');
  };

  return (
    <header className="bg-dark-navy shadow fixed w-full z-50 border-b-4 border-primary-main">
      <nav className="container mx-auto px-6 py-3">
        <div className="flex items-center justify-between">
          <motion.div initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.35 }}>
            <Link href="/" className="text-2xl font-bold text-white hover:text-primary-light transition-colors">IGFV</Link>
          </motion.div>

          {/* Desktop */}
          <div className="hidden md:flex items-center space-x-6">
            {navItems.map((item) => (
              <Link
                key={item.href}
                href={item.href}
                className={`text-white hover:underline hover:decoration-primary-main hover:underline-offset-4 transition-all ${isActive(item.href) ? 'underline decoration-primary-main underline-offset-4' : ''}`}
              >
                {item.label}
              </Link>
            ))}

            {/* Discord CTA */}
            <a
              href="https://discord.gg/invite/Jvrgy6EEQn"
              target="_blank"
              rel="noopener noreferrer"
              className="ml-2 px-4 py-2 bg-primary-main text-white rounded-md font-semibold hover:bg-primary-darkest transition"
            >
              Discord
            </a>
          </div>

          {/* Mobile toggle */}
          <div className="md:hidden">
            <button aria-label="Toggle menu" onClick={() => setIsOpen(!isOpen)} className="text-white">
              {isOpen ? <XMarkIcon className="h-6 w-6" /> : <Bars3Icon className="h-6 w-6" />}
            </button>
          </div>
        </div>

        {/* Mobile menu */}
        {isOpen && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.25 }} className="md:hidden mt-3">
            <div className="flex flex-col space-y-2">
              {navItems.map((item) => (
                <Link
                  key={item.href}
                  href={item.href}
                  onClick={() => setIsOpen(false)}
                  className={`block px-3 py-2 rounded-md text-white hover:bg-primary-main/20 hover:underline hover:decoration-primary-main hover:underline-offset-4 ${isActive(item.href) ? 'bg-primary-main/20 underline decoration-primary-main underline-offset-4' : ''}`}
                >
                  {item.label}
                </Link>
              ))}

              {/* Mobile Discord CTA */}
              <a
                href="https://discord.gg/invite/Jvrgy6EEQn"
                target="_blank"
                rel="noopener noreferrer"
                className="block mt-2 px-3 py-2 rounded-md bg-primary-main text-white text-center font-semibold hover:bg-primary-darkest"
                onClick={() => setIsOpen(false)}
              >
                Join Discord
              </a>
            </div>
          </motion.div>
        )}
      </nav>
    </header>
  );
};
