// src/components/Footer/Footer.tsx
'use client';

import { FaDiscord, FaXTwitter, FaFacebook } from 'react-icons/fa6';

export const Footer = () => {
  const currentYear = new Date().getFullYear();


  const socials = [
    { href: 'https://discord.gg/invite/Jvrgy6EEQn', label: 'Discord', icon: FaDiscord },
    { href: 'https://x.com/intrstlrgdfelas', label: 'X (Twitter)', icon: FaXTwitter },
    { href: 'https://www.facebook.com/interstellargoodfella', label: 'Facebook', icon: FaFacebook },
  ];

  return (
    <footer className="bg-dark-navy py-6 border-t-4 border-primary-main">
      <div className="container mx-auto px-6">
        <div className="flex items-center justify-between">
          <div className="text-white text-sm text-left">© {currentYear} Interstellar Goodfellas - IGFV. All rights reserved.</div>

          <div className="flex items-center space-x-4">
            {socials.map((s) => (
              <a key={s.href} href={s.href} target="_blank" rel="noopener noreferrer" aria-label={s.label} className="text-white hover:text-primary-light transition-colors">
                <s.icon className="h-5 w-5" />
              </a>
            ))}
          </div>
        </div>
      </div>
    </footer>
  );
};

// src/lib/components/Footer.svelte
<script lang="ts">
	import { DiscordBrands, XTwitterBrands, FacebookBrands } from 'svelte-awesome-icons';

	const currentYear = new Date().getFullYear();

	const socialLinks = [
		{ href: 'https://discord.gg/igfv', icon: DiscordBrands, label: 'Discord' },
		{ href: 'https://twitter.com/', icon: XTwitterBrands, label: 'X / Twitter' },
		{ href: 'https://facebook.com/', icon: FacebookBrands, label: 'Facebook' }
	];
</script>

<footer class="border-t-4 border-primary-main bg-dark-navy">
	<div
		class="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-4 py-8 sm:flex-row sm:px-6 lg:px-8"
	>
		<!-- Copyright -->
		<p class="text-sm text-gray-400">
			&copy; {currentYear} Interstellar Goodfellas - IGFV. All rights reserved.
		</p>

		<!-- Social Links -->
		<div class="flex items-center gap-4">
			{#each socialLinks as link (link.href)}
				<a
					href={link.href}
					target="_blank"
					rel="noopener noreferrer"
					class="text-gray-400 transition-colors hover:text-white"
					aria-label={link.label}
				>
					<link.icon class="h-5 w-5" />
				</a>
			{/each}
		</div>
	</div>
</footer>
