// src/components/ScrollDown/ScrollDown.tsx
'use client';

import { motion } from 'framer-motion';
import { FaChevronDown } from 'react-icons/fa';

export default function ScrollDown() {
  const handleScroll = () => {
    window.scrollBy({ top: window.innerHeight, behavior: 'smooth' });
  };

  return (
    <motion.button
      onClick={handleScroll}
      className="absolute bottom-10 left-1/2 -translate-x-1/2 z-30 flex flex-col items-center gap-2 focus:outline-none focus:ring-2 focus:ring-primary-light rounded-lg"
      animate={{ y: [0, 10, 0] }}
      transition={{ duration: 2, repeat: Infinity }}
      aria-label="Scroll down to see more content"
    >
      <span className="text-white text-sm font-semibold uppercase tracking-widest">Scroll</span>
      <motion.div
        animate={{ opacity: [0.5, 1, 0.5] }}
        transition={{ duration: 2, repeat: Infinity }}
        className="text-primary-light"
      >
        <FaChevronDown className="text-2xl" />
      </motion.div>
    </motion.button>
  );
}

// src/lib/components/ScrollDown.svelte
<script lang="ts">
	import { ChevronDownSolid } from 'svelte-awesome-icons';

	function scrollDown() {
		window.scrollTo({
			top: window.innerHeight,
			behavior: 'smooth'
		});
	}
</script>

<button
	onclick={scrollDown}
	class="group absolute bottom-8 left-1/2 z-10 flex -translate-x-1/2 cursor-pointer flex-col items-center gap-2 border-none bg-transparent text-white/50 transition-colors duration-300 hover:text-white"
	aria-label="Scroll down"
>
	<span class="font-mono text-xs tracking-widest uppercase">Scroll</span>
	<span class="chevron-icon block">
		<ChevronDownSolid class="size-5" />
	</span>
</button>

<style>
	@keyframes bounce {
		0%,
		100% {
			transform: translateY(0);
		}
		50% {
			transform: translateY(8px);
		}
	}

	.chevron-icon {
		animation: bounce 2s ease-in-out infinite;
	}

	.group:hover .chevron-icon {
		animation-duration: 1s;
	}
</style>
