// src/routes/members/+page.svelte
<script lang="ts">
	import { inview } from '$lib/actions/inview';
	import {
		UsersSolid,
		StarSolid,
		ClockSolid,
		GlobeAmericasSolid,
		HandshakeSolid,
		FireSolid,
		ExternalLinkAltSolid,
		CompassSolid
	} from 'svelte-awesome-icons';
	import { resolve } from '$app/paths';
</script>

<!-- Hero Section -->
<section class="relative overflow-hidden border-b border-primary-main/20">
	<div
		class="absolute inset-0 bg-gradient-to-b from-primary-main/5 via-transparent to-transparent"
	></div>
	<div class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-32">
		<div use:inview class="inview-hidden mx-auto max-w-3xl text-center">
			<div
				class="mb-6 inline-flex items-center gap-2 rounded-full border border-primary-main/30 bg-primary-main/10 px-4 py-1.5 text-sm text-primary-light"
			>
				<UsersSolid class="h-4 w-4" />
				<span>Members</span>
			</div>
			<h1 class="text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl">
				Squadron <span class="text-primary-main">Members</span>
			</h1>
			<p class="mt-6 text-lg leading-relaxed text-gray-300">
				Meet the commanders who make IGFV the vibrant community it is. From our leadership team to
				our active members, every commander plays a vital role in our squadron.
			</p>
		</div>
	</div>
</section>

<!-- Leadership Team -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			Leadership <span class="text-primary-main">Team</span>
		</h2>
	</div>
	<div class="grid grid-cols-1 gap-6 md:grid-cols-3">
		<div use:inview={{ delay: 100 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div class="mb-4 flex items-center gap-4">
					<div
						class="flex h-14 w-14 items-center justify-center rounded-full bg-primary-main/20 text-xl font-bold text-primary-light"
					>
						SK
					</div>
					<div>
						<h3 class="text-lg font-bold text-white">Skalfinn</h3>
						<p class="text-xs text-gray-400">Squadron Leader</p>
					</div>
				</div>
				<div
					class="mb-3 inline-block rounded-full border border-yellow-500/30 bg-yellow-500/10 px-3 py-0.5 text-xs font-medium text-yellow-400"
				>
					Founder
				</div>
				<div class="space-y-2 text-sm text-gray-400">
					<p class="flex items-center gap-2">
						<StarSolid class="h-4 w-4 text-primary-main" /> Focus: Overall leadership & strategy
					</p>
					<p class="flex items-center gap-2">
						<ClockSolid class="h-4 w-4 text-primary-main" /> Timezone: UTC+1
					</p>
					<p class="flex items-center gap-2">
						<ExternalLinkAltSolid class="h-4 w-4 text-primary-main" />
						<a
							href="https://inara.cz"
							target="_blank"
							rel="noopener noreferrer"
							class="text-primary-light hover:underline">Inara Profile</a
						>
					</p>
				</div>
			</div>
		</div>
		<div use:inview={{ delay: 150 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div class="mb-4 flex items-center gap-4">
					<div
						class="flex h-14 w-14 items-center justify-center rounded-full bg-primary-main/20 text-xl font-bold text-primary-light"
					>
						DS
					</div>
					<div>
						<h3 class="text-lg font-bold text-white">Don Samen</h3>
						<p class="text-xs text-gray-400">Founder</p>
					</div>
				</div>
				<div
					class="mb-3 inline-block rounded-full border border-yellow-500/30 bg-yellow-500/10 px-3 py-0.5 text-xs font-medium text-yellow-400"
				>
					Founder
				</div>
				<div class="space-y-2 text-sm text-gray-400">
					<p class="flex items-center gap-2">
						<StarSolid class="h-4 w-4 text-primary-main" /> Focus: Squadron operations & expansion
					</p>
					<p class="flex items-center gap-2">
						<ClockSolid class="h-4 w-4 text-primary-main" /> Timezone: UTC+1
					</p>
					<p class="flex items-center gap-2">
						<ExternalLinkAltSolid class="h-4 w-4 text-primary-main" />
						<a
							href="https://inara.cz"
							target="_blank"
							rel="noopener noreferrer"
							class="text-primary-light hover:underline">Inara Profile</a
						>
					</p>
				</div>
			</div>
		</div>
		<div use:inview={{ delay: 200 }} class="inview-hidden group">
			<div
				class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-6 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div class="mb-4 flex items-center gap-4">
					<div
						class="flex h-14 w-14 items-center justify-center rounded-full bg-primary-main/20 text-xl font-bold text-primary-light"
					>
						TV
					</div>
					<div>
						<h3 class="text-lg font-bold text-white">Twisted VorteK</h3>
						<p class="text-xs text-gray-400">Squadron Manager</p>
					</div>
				</div>
				<div
					class="mb-3 inline-block rounded-full border border-blue-500/30 bg-blue-500/10 px-3 py-0.5 text-xs font-medium text-blue-400"
				>
					Manager
				</div>
				<div class="space-y-2 text-sm text-gray-400">
					<p class="flex items-center gap-2">
						<StarSolid class="h-4 w-4 text-primary-main" /> Focus: BGS operations & recruitment
					</p>
					<p class="flex items-center gap-2">
						<ClockSolid class="h-4 w-4 text-primary-main" /> Timezone: UTC+2
					</p>
					<p class="flex items-center gap-2">
						<ExternalLinkAltSolid class="h-4 w-4 text-primary-main" />
						<a
							href="https://inara.cz"
							target="_blank"
							rel="noopener noreferrer"
							class="text-primary-light hover:underline">Inara Profile</a
						>
					</p>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Active Members -->
<section
	class="border-t border-primary-main/20 bg-gradient-to-b from-dark-bg via-primary-main/5 to-dark-bg"
>
	<div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
		<div use:inview class="inview-hidden">
			<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
				Active <span class="text-primary-main">Members</span>
			</h2>
		</div>
		<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
			<div use:inview={{ delay: 100 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-5 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div class="mb-3 flex items-center gap-3">
						<div
							class="flex h-10 w-10 items-center justify-center rounded-full bg-primary-main/20 text-sm font-bold text-primary-light"
						>
							SM
						</div>
						<div>
							<h3 class="font-bold text-white">StarMiner</h3>
							<div
								class="inline-block rounded-full bg-primary-main/10 px-2 py-0.5 text-xs font-medium text-primary-light"
							>
								Member
							</div>
						</div>
					</div>
					<div class="space-y-1 text-xs text-gray-400">
						<p class="flex items-center gap-1.5">
							<FireSolid class="h-3 w-3 text-primary-main" /> Focus: Mining & Trading
						</p>
						<p class="flex items-center gap-1.5">
							<CompassSolid class="h-3 w-3 text-primary-main" /> Specialty: Deep core mining
						</p>
						<p class="flex items-center gap-1.5">
							<ClockSolid class="h-3 w-3 text-primary-main" /> Timezone: UTC+8
						</p>
					</div>
				</div>
			</div>
			<div use:inview={{ delay: 130 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-5 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div class="mb-3 flex items-center gap-3">
						<div
							class="flex h-10 w-10 items-center justify-center rounded-full bg-primary-main/20 text-sm font-bold text-primary-light"
						>
							VK
						</div>
						<div>
							<h3 class="font-bold text-white">VoidKraken</h3>
							<div
								class="inline-block rounded-full bg-primary-main/10 px-2 py-0.5 text-xs font-medium text-primary-light"
							>
								Member
							</div>
						</div>
					</div>
					<div class="space-y-1 text-xs text-gray-400">
						<p class="flex items-center gap-1.5">
							<FireSolid class="h-3 w-3 text-primary-main" /> Focus: Exploration & BGS
						</p>
						<p class="flex items-center gap-1.5">
							<CompassSolid class="h-3 w-3 text-primary-main" /> Specialty: System scanning
						</p>
						<p class="flex items-center gap-1.5">
							<ClockSolid class="h-3 w-3 text-primary-main" /> Timezone: UTC+0
						</p>
					</div>
				</div>
			</div>
			<div use:inview={{ delay: 160 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-5 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div class="mb-3 flex items-center gap-3">
						<div
							class="flex h-10 w-10 items-center justify-center rounded-full bg-primary-main/20 text-sm font-bold text-primary-light"
						>
							NR
						</div>
						<div>
							<h3 class="font-bold text-white">NovaRunner</h3>
							<div
								class="inline-block rounded-full bg-primary-main/10 px-2 py-0.5 text-xs font-medium text-primary-light"
							>
								Member
							</div>
						</div>
					</div>
					<div class="space-y-1 text-xs text-gray-400">
						<p class="flex items-center gap-1.5">
							<FireSolid class="h-3 w-3 text-primary-main" /> Focus: Combat & Engineering
						</p>
						<p class="flex items-center gap-1.5">
							<CompassSolid class="h-3 w-3 text-primary-main" /> Specialty: Ship optimization
						</p>
						<p class="flex items-center gap-1.5">
							<ClockSolid class="h-3 w-3 text-primary-main" /> Timezone: UTC-5
						</p>
					</div>
				</div>
			</div>
			<div use:inview={{ delay: 190 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-5 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div class="mb-3 flex items-center gap-3">
						<div
							class="flex h-10 w-10 items-center justify-center rounded-full bg-primary-main/20 text-sm font-bold text-primary-light"
						>
							QF
						</div>
						<div>
							<h3 class="font-bold text-white">QuantumFox</h3>
							<div
								class="inline-block rounded-full bg-primary-main/10 px-2 py-0.5 text-xs font-medium text-primary-light"
							>
								Member
							</div>
						</div>
					</div>
					<div class="space-y-1 text-xs text-gray-400">
						<p class="flex items-center gap-1.5">
							<FireSolid class="h-3 w-3 text-primary-main" /> Focus: Trading & Hauling
						</p>
						<p class="flex items-center gap-1.5">
							<CompassSolid class="h-3 w-3 text-primary-main" /> Specialty: Route optimization
						</p>
						<p class="flex items-center gap-1.5">
							<ClockSolid class="h-3 w-3 text-primary-main" /> Timezone: UTC+3
						</p>
					</div>
				</div>
			</div>
			<div use:inview={{ delay: 220 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-5 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div class="mb-3 flex items-center gap-3">
						<div
							class="flex h-10 w-10 items-center justify-center rounded-full bg-primary-main/20 text-sm font-bold text-primary-light"
						>
							PS
						</div>
						<div>
							<h3 class="font-bold text-white">PulsarSage</h3>
							<div
								class="inline-block rounded-full bg-primary-main/10 px-2 py-0.5 text-xs font-medium text-primary-light"
							>
								Member
							</div>
						</div>
					</div>
					<div class="space-y-1 text-xs text-gray-400">
						<p class="flex items-center gap-1.5">
							<FireSolid class="h-3 w-3 text-primary-main" /> Focus: Exploration & Research
						</p>
						<p class="flex items-center gap-1.5">
							<CompassSolid class="h-3 w-3 text-primary-main" /> Specialty: Galactic discoveries
						</p>
						<p class="flex items-center gap-1.5">
							<ClockSolid class="h-3 w-3 text-primary-main" /> Timezone: UTC-8
						</p>
					</div>
				</div>
			</div>
			<div use:inview={{ delay: 250 }} class="inview-hidden group">
				<div
					class="bg-dark/50 h-full rounded-lg border border-primary-main/30 p-5 shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
				>
					<div class="mb-3 flex items-center gap-3">
						<div
							class="flex h-10 w-10 items-center justify-center rounded-full bg-primary-main/20 text-sm font-bold text-primary-light"
						>
							AE
						</div>
						<div>
							<h3 class="font-bold text-white">AetherEcho</h3>
							<div
								class="inline-block rounded-full bg-primary-main/10 px-2 py-0.5 text-xs font-medium text-primary-light"
							>
								Member
							</div>
						</div>
					</div>
					<div class="space-y-1 text-xs text-gray-400">
						<p class="flex items-center gap-1.5">
							<FireSolid class="h-3 w-3 text-primary-main" /> Focus: BGS & Community
						</p>
						<p class="flex items-center gap-1.5">
							<CompassSolid class="h-3 w-3 text-primary-main" /> Specialty: Faction management
						</p>
						<p class="flex items-center gap-1.5">
							<ClockSolid class="h-3 w-3 text-primary-main" /> Timezone: UTC+5.5
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Stats -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
	<div use:inview class="inview-hidden">
		<h2 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">
			Squadron <span class="text-primary-main">Stats</span>
		</h2>
	</div>
	<div class="grid grid-cols-1 gap-6 sm:grid-cols-3">
		<div use:inview={{ delay: 100 }} class="inview-hidden group">
			<div
				class="bg-dark/50 rounded-lg border border-primary-main/30 p-8 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-primary-main/20 text-primary-light"
				>
					<UsersSolid class="h-7 w-7" />
				</div>
				<p class="text-4xl font-bold text-white">100+</p>
				<p class="mt-2 text-sm text-gray-400">Active Members</p>
			</div>
		</div>
		<div use:inview={{ delay: 200 }} class="inview-hidden group">
			<div
				class="bg-dark/50 rounded-lg border border-primary-main/30 p-8 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-primary-main/20 text-primary-light"
				>
					<GlobeAmericasSolid class="h-7 w-7" />
				</div>
				<p class="text-4xl font-bold text-white">6+</p>
				<p class="mt-2 text-sm text-gray-400">Timezones Covered</p>
			</div>
		</div>
		<div use:inview={{ delay: 300 }} class="inview-hidden group">
			<div
				class="bg-dark/50 rounded-lg border border-primary-main/30 p-8 text-center shadow-glow backdrop-blur-sm transition-all duration-300 hover:border-primary-main/50 hover:shadow-glow-hover"
			>
				<div
					class="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-primary-main/20 text-primary-light"
				>
					<StarSolid class="h-7 w-7" />
				</div>
				<p class="text-4xl font-bold text-white">5+</p>
				<p class="mt-2 text-sm text-gray-400">Years of Experience</p>
			</div>
		</div>
	</div>
</section>

<!-- Join CTA -->
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
	<div use:inview class="inview-hidden">
		<div
			class="to-dark/50 rounded-lg border border-primary-main/30 bg-gradient-to-br from-primary-main/10 p-8 text-center shadow-glow backdrop-blur-sm sm:p-12"
		>
			<h2 class="text-3xl font-bold text-white sm:text-4xl">
				Join Our <span class="text-primary-main">Community</span>
			</h2>
			<p class="mx-auto mt-4 max-w-2xl text-gray-300">
				Become part of a growing community of commanders who share your passion for exploration and
				discovery.
			</p>
			<a
				href={resolve('/join')}
				class="mt-6 inline-flex items-center gap-2 rounded-lg bg-primary-main px-8 py-3 font-semibold text-white transition-all duration-300 hover:bg-primary-light hover:shadow-glow-hover"
			>
				<HandshakeSolid class="h-5 w-5" />
				Join IGFV Today
			</a>
		</div>
	</div>
</section>

// src/app/members/page.tsx
'use client';

import { FaUsers, FaMedal, FaTrophy, FaExternalLinkAlt } from 'react-icons/fa';
import { motion } from 'framer-motion';
import Link from 'next/link';

export default function MembersPage() {
  const leaders = [
    {
      name: 'Skalfinn',
      rank: 'Commander',
      title: 'Founder & Leader',
      focus: 'Exploration & Operations',
      tz: 'UTC+1',
      inaraUrl: 'https://inara.cz/cmdr/skalfinn/',
    },
    {
      name: 'Don Samen',
      rank: 'Vice Admiral',
      title: 'Operations Director',
      focus: 'BGS & Mining',
      tz: 'UTC+1',
      inaraUrl: 'https://inara.cz/cmdr/don%20samen/',
    },
    {
      name: 'Twisted VorteK',
      rank: 'Rear Admiral',
      title: 'Community Manager',
      focus: 'Community & Events',
      tz: 'UTC-5',
      inaraUrl: 'https://inara.cz/cmdr/twisted%20vortec/',
    },
  ];

  const sampleMembers = [
    { name: 'Nova', rank: 'Veteran', focus: 'Exploration', specialty: 'Elite Explorer', tz: 'UTC+0' },
    { name: 'RedMiner', rank: 'Officer', focus: 'Mining', specialty: 'Master Miner', tz: 'UTC+2' },
    { name: 'FleetLeader', rank: 'Officer', focus: 'Combat', specialty: 'Wing Specialist', tz: 'UTC-5' },
    { name: 'TradeKing', rank: 'Member', focus: 'Trading', specialty: 'Tycoon', tz: 'UTC+0' },
    { name: 'Explorer42', rank: 'Member', focus: 'Exploration', specialty: 'Pathfinder', tz: 'UTC+8' },
    { name: 'CombatPilot', rank: 'Member', focus: 'Combat', specialty: 'Expert', tz: 'UTC-3' },
  ];

  return (
    <div className="min-h-screen py-12">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Page Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="mb-12"
        >
          <div className="bg-gradient-to-r from-norway-red/20 to-norway-blue/20 border border-norway-red/30 rounded-lg p-8 md:p-12">
            <div className="flex items-center gap-4 mb-4">
              <FaUsers className="text-4xl md:text-5xl text-norway-red" />
              <h1 className="text-4xl md:text-5xl font-bold text-white">Squadron Members</h1>
            </div>
            <p className="text-lg text-gray-300">100+ Commanders across multiple timezones united in exploration and cooperation.</p>
          </div>
        </motion.div>

        {/* Leadership Section */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="mb-16"
        >
          <h2 className="text-3xl font-bold text-white mb-8 flex items-center gap-3">
            <FaMedal className="text-norway-red" />
            Leadership
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {leaders.map((leader, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.4, delay: 0.1 * idx }}
                className="bg-gradient-to-br from-norway-red/20 to-dark/50 backdrop-blur-sm rounded-lg p-6 shadow-glow border-2 border-norway-red/40"
              >
                <div className="mb-4">
                  <span className="inline-block px-3 py-1 bg-norway-red/30 text-norway-red text-sm font-bold rounded-full mb-3">
                    {leader.rank}
                  </span>
                  <h3 className="text-2xl font-bold text-white mb-1">CMDR {leader.name}</h3>
                  <p className="text-norway-red font-semibold text-sm">{leader.title}</p>
                </div>

                <div className="space-y-2 mb-4 text-gray-300 text-sm">
                  <p>
                    <span className="text-norway-red">Focus:</span> {leader.focus}
                  </p>
                  <p>
                    <span className="text-norway-red">Timezone:</span> {leader.tz}
                  </p>
                </div>

                <a
                  href={leader.inaraUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 text-norway-red hover:text-norway-white bg-norway-red/10 hover:bg-norway-red transition-all px-3 py-2 rounded text-sm font-semibold"
                >
                  View on Inara <FaExternalLinkAlt className="text-xs" />
                </a>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Active Members */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mb-12"
        >
          <h2 className="text-3xl font-bold text-white mb-8 flex items-center gap-3">
            <FaTrophy className="text-norway-red" />
            Active Members
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {sampleMembers.map((member, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.4, delay: 0.05 * idx }}
                className="bg-dark/50 backdrop-blur-sm rounded-lg p-5 shadow-glow border border-norway-red/20 hover:border-norway-red/60 transition-all"
              >
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <h3 className="text-lg font-bold text-white">CMDR {member.name}</h3>
                    <p className="text-gray-400 text-sm">{member.rank}</p>
                  </div>
                  <span className="px-2 py-1 bg-norway-red/20 text-norway-red text-xs font-bold rounded">
                    {member.tz}
                  </span>
                </div>

                <div className="space-y-1 text-gray-300 text-sm mb-4">
                  <p>
                    <span className="text-norway-red">Focus:</span> {member.focus}
                  </p>
                  <p>
                    <span className="text-norway-red">Specialty:</span> {member.specialty}
                  </p>
                </div>

                <div className="pt-3 border-t border-norway-red/10">
                  <p className="text-xs text-gray-500">Click on name to view Inara profile</p>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Stats & Info */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12"
        >
          <div className="bg-dark/50 backdrop-blur-sm rounded-lg p-6 shadow-glow border border-norway-blue/20">
            <p className="text-gray-400 text-sm uppercase tracking-wider mb-2">Total Members</p>
            <p className="text-4xl font-bold text-norway-red">100+</p>
            <p className="text-gray-500 text-xs mt-2">And growing every month</p>
          </div>

          <div className="bg-dark/50 backdrop-blur-sm rounded-lg p-6 shadow-glow border border-norway-blue/20">
            <p className="text-gray-400 text-sm uppercase tracking-wider mb-2">Timezones</p>
            <p className="text-4xl font-bold text-norway-red">6+</p>
            <p className="text-gray-500 text-xs mt-2">Global coverage</p>
          </div>

          <div className="bg-dark/50 backdrop-blur-sm rounded-lg p-6 shadow-glow border border-norway-blue/20">
            <p className="text-gray-400 text-sm uppercase tracking-wider mb-2">Avg Experience</p>
            <p className="text-4xl font-bold text-norway-red">5+ yrs</p>
            <p className="text-gray-500 text-xs mt-2">Per commander</p>
          </div>
        </motion.div>

        {/* Join CTA */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="bg-gradient-to-r from-norway-red/20 to-norway-blue/20 border border-norway-red/30 rounded-lg p-8 text-center"
        >
          <h3 className="text-2xl font-bold text-white mb-4">Interested in Joining?</h3>
          <p className="text-gray-300 mb-6 max-w-2xl mx-auto">
            We welcome experienced commanders and newcomers alike. All playstyles are valued in IGFV.
          </p>
          <Link
            href="/join"
            className="inline-block px-8 py-3 bg-norway-red hover:bg-norway-red/80 text-white font-bold rounded-lg transition-colors"
          >
            Apply to Join
          </Link>
        </motion.div>
      </div>
    </div>
  );
}
