// src/lib/components/ComingSoon.svelte
<script lang="ts">
	import { RocketSolid, GamepadSolid, CodeSolid } from 'svelte-awesome-icons';

	let {
		title = 'Coming Soon',
		message = 'This feature is currently in development...',
		progress = 70,
		progressLabel = 'Progress: 70% - Debugging final boss encounter'
	} = $props();
</script>

<div class="flex min-h-screen items-center justify-center bg-dark-bg px-4">
	<div class="flex max-w-lg flex-col items-center gap-8 text-center">
		<!-- Animated Icons -->
		<div class="flex items-center gap-6">
			<div class="animate-bob">
				<RocketSolid class="h-10 w-10 text-primary-main" />
			</div>
			<div class="animate-pulse-slow">
				<GamepadSolid class="h-10 w-10 text-norway-blue" />
			</div>
			<div class="animate-bob animation-delay-500">
				<CodeSolid class="h-10 w-10 text-orange-400" />
			</div>
		</div>

		<!-- Heading -->
		<h1
			class="bg-gradient-to-r from-orange-400 to-red-600 bg-clip-text text-4xl font-extrabold tracking-widest text-transparent uppercase sm:text-5xl"
		>
			{title}
		</h1>

		<!-- Message -->
		<p class="max-w-md text-lg text-gray-400">{message}</p>

		<!-- Progress Bar -->
		<div class="w-full max-w-sm">
			<div class="h-3 overflow-hidden rounded-full bg-dark-slate1">
				<div
					class="animate-progress h-full rounded-full bg-gradient-to-r from-primary-main to-orange-400"
				></div>
			</div>
		</div>

		<!-- Progress Label -->
		<p class="font-mono text-sm text-gray-500">{progressLabel}</p>

		<!-- Return Link -->
		<a
			href="/"
			class="inline-flex items-center gap-2 rounded-md bg-primary-main px-6 py-3 text-sm font-bold tracking-wider text-white uppercase transition-all hover:bg-primary-light hover:shadow-glow-hover"
		>
			Return to Base
		</a>
	</div>
</div>

<style>
	@keyframes bob {
		0%,
		100% {
			transform: translateY(0);
		}
		50% {
			transform: translateY(-10px);
		}
	}

	@keyframes pulse-slow {
		0%,
		100% {
			opacity: 1;
			transform: scale(1);
		}
		50% {
			opacity: 0.7;
			transform: scale(1.1);
		}
	}

	@keyframes progress-grow {
		from {
			width: 10%;
		}
		to {
			width: 70%;
		}
	}

	.animate-bob {
		animation: bob 2s ease-in-out infinite;
	}

	.animate-pulse-slow {
		animation: pulse-slow 2.5s ease-in-out infinite;
	}

	.animation-delay-500 {
		animation-delay: 500ms;
	}

	.animate-progress {
		animation: progress-grow 2.5s ease-out forwards;
	}
</style>

// src/components/ComingSoon/ComingSoon.tsx
'use client';

import Link from 'next/link';
import { MotionDiv } from '@/components/Motion/MotionDiv';
import { FaRocket, FaGamepad, FaCode } from 'react-icons/fa';

export const ComingSoon = () => {
  return (
    <div className="min-h-[80vh] flex items-center justify-center px-4">
      <div className="text-center max-w-3xl">
        <MotionDiv
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="space-y-8"
        >
          <div className="flex justify-center space-x-4 text-5xl text-primary">
            <MotionDiv
              initial={{ rotate: -10 }}
              animate={{ rotate: 10 }}
              transition={{ repeat: Infinity, repeatType: "reverse", duration: 2 }}
            >
              <FaRocket />
            </MotionDiv>
            <MotionDiv
              initial={{ scale: 0.9 }}
              animate={{ scale: 1.1 }}
              transition={{ repeat: Infinity, repeatType: "reverse", duration: 1.5 }}
            >
              <FaGamepad />
            </MotionDiv>
            <MotionDiv
              initial={{ opacity: 0.7 }}
              animate={{ opacity: 1 }}
              transition={{ repeat: Infinity, repeatType: "reverse", duration: 1.8 }}
            >
              <FaCode />
            </MotionDiv>
          </div>

          <h1 className="text-4xl md:text-6xl font-bold bg-gradient-to-r from-orange-400 to-red-600 bg-clip-text text-transparent">
            Level Loading...
          </h1>
          
          <div className="text-lg text-gray-300">
            <p className="mb-4">This feature is currently in development and will be released soon!</p>
            <p className="text-sm text-gray-400">
              Our dev squad is working overtime to bring you an epic experience.
              <br />XP boost activated: +200% coding speed!
            </p>
          </div>
          
          <div className="w-64 h-4 mx-auto bg-gray-700 rounded-full overflow-hidden">
            <MotionDiv
              className="h-full bg-gradient-to-r from-orange-500 to-red-600"
              initial={{ width: '10%' }}
              animate={{ width: '70%' }}
              transition={{ duration: 2, ease: "easeInOut" }}
            >
              <div></div>
            </MotionDiv>
          </div>
          
          <p className="text-sm text-gray-500">
            Progress: 70% - Debugging final boss encounter
          </p>
          
          <div className="pt-4">
            <Link 
              href="/"
              className="inline-block px-8 py-3 bg-primary hover:bg-primary-dark transition-colors rounded-lg shadow-glow hover:shadow-glow-hover"
            >
              Return to Base
            </Link>
          </div>
        </MotionDiv>
      </div>
    </div>
  );
};
